// Code generated by Fern. DO NOT EDIT.

package environments_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	chroniclego "github.com/chronicle-labs-ai/chronicle-go"
	client "github.com/chronicle-labs-ai/chronicle-go/client"
	option "github.com/chronicle-labs-ai/chronicle-go/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestEnvironmentsListEnvironmentsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	_, invocationErr := client.Environments.ListEnvironments(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestEnvironmentsListEnvironmentsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestEnvironmentsListEnvironmentsWithWireMock", "GET", "/v1/environments", nil, 1)
}

func TestEnvironmentsCreateEnvironmentWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &chroniclego.CreateEnvironmentRequest{
		Slug:  "support-sandbox",
		Label: "Support sandbox",
		Description: chroniclego.String(
			"Isolated environment for support-agent backtests.",
		),
	}
	_, invocationErr := client.Environments.CreateEnvironment(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestEnvironmentsCreateEnvironmentWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestEnvironmentsCreateEnvironmentWithWireMock", "POST", "/v1/environments", nil, 1)
}

func TestEnvironmentsGetEnvironmentWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &chroniclego.GetEnvironmentRequest{
		EnvironmentID: "environment_id",
	}
	_, invocationErr := client.Environments.GetEnvironment(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestEnvironmentsGetEnvironmentWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestEnvironmentsGetEnvironmentWithWireMock", "GET", "/v1/environments/environment_id", nil, 1)
}

func TestEnvironmentsListEnvironmentVersionsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &chroniclego.ListEnvironmentVersionsRequest{
		EnvironmentID: "environment_id",
	}
	_, invocationErr := client.Environments.ListEnvironmentVersions(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestEnvironmentsListEnvironmentVersionsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestEnvironmentsListEnvironmentVersionsWithWireMock", "GET", "/v1/environments/environment_id/versions", nil, 1)
}

func TestEnvironmentsCreateEnvironmentVersionWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &chroniclego.CreateEnvironmentVersionRequest{
		EnvironmentID: "environment_id",
		Version:       "version",
	}
	_, invocationErr := client.Environments.CreateEnvironmentVersion(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestEnvironmentsCreateEnvironmentVersionWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestEnvironmentsCreateEnvironmentVersionWithWireMock", "POST", "/v1/environments/environment_id/versions", nil, 1)
}

func TestEnvironmentsGetEnvironmentVersionWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &chroniclego.GetEnvironmentVersionRequest{
		EnvironmentID:   "environment_id",
		VersionSelector: "version_selector",
	}
	_, invocationErr := client.Environments.GetEnvironmentVersion(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestEnvironmentsGetEnvironmentVersionWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestEnvironmentsGetEnvironmentVersionWithWireMock", "GET", "/v1/environments/environment_id/versions/version_selector", nil, 1)
}

func TestEnvironmentsCompileEnvironmentVersionWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &chroniclego.CompileEnvironmentRequest{
		EnvironmentID:     "environment_id",
		VersionSelector:   "version_selector",
		DatasetSnapshotID: "datasetSnapshotId",
		ScenarioID:        "scenarioId",
	}
	_, invocationErr := client.Environments.CompileEnvironmentVersion(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestEnvironmentsCompileEnvironmentVersionWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestEnvironmentsCompileEnvironmentVersionWithWireMock", "POST", "/v1/environments/environment_id/versions/version_selector/compile", nil, 1)
}
