// Code generated by Fern. DO NOT EDIT.

package timeline

import (
	context "context"

	chroniclego "github.com/chronicle-labs-ai/chronicle-go"
	core "github.com/chronicle-labs-ai/chronicle-go/core"
	internal "github.com/chronicle-labs-ai/chronicle-go/internal"
	option "github.com/chronicle-labs-ai/chronicle-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Requires scope events:read or events:write. Cursor paginated, newest first.
//
// Pass `cursor` from `next_cursor` to read the following page, and stop when `has_more` is false. The cursor is opaque: it is a keyset over `(event_time, event_id)`, it is exclusive so a row cannot repeat across pages, and its encoding may change without notice. Do not parse or construct one.
//
// `include_linked=true` selects a different read that also returns causally linked events. That read is not paginated: it returns one page with `has_more` false, and it cannot be combined with `limit` or `cursor`. `since` is only available on that read, because the paginated read has no time filter.
//
// Example:
//
//	request := &chroniclego.GetTimelineRequest{
//	    EntityType: "entity_type",
//	    EntityID: "entity_id",
//	}
//	client.Timeline.GetTimeline(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetTimeline(
	ctx context.Context,
	request *chroniclego.GetTimelineRequest,
	opts ...option.RequestOption,
) (*chroniclego.EventPage, error) {
	response, err := c.WithRawResponse.GetTimeline(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
