// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/chronicle-labs-ai/chronicle-go/internal"
	big "math/big"
	time "time"
)

var (
	createSdkKeyRequestFieldName   = big.NewInt(1 << 0)
	createSdkKeyRequestFieldScopes = big.NewInt(1 << 1)
)

type CreateSdkKeyRequest struct {
	Name   string                          `json:"name" url:"-"`
	Scopes []CreateSdkKeyRequestScopesItem `json:"scopes" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateSdkKeyRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSdkKeyRequest) SetName(name string) {
	c.Name = name
	c.require(createSdkKeyRequestFieldName)
}

// SetScopes sets the Scopes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSdkKeyRequest) SetScopes(scopes []CreateSdkKeyRequestScopesItem) {
	c.Scopes = scopes
	c.require(createSdkKeyRequestFieldScopes)
}

func (c *CreateSdkKeyRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateSdkKeyRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateSdkKeyRequest(body)
	return nil
}

func (c *CreateSdkKeyRequest) MarshalJSON() ([]byte, error) {
	type embed CreateSdkKeyRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	revokeSdkKeyRequestFieldKeyID = big.NewInt(1 << 0)
)

type RevokeSdkKeyRequest struct {
	KeyID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RevokeSdkKeyRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetKeyID sets the KeyID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RevokeSdkKeyRequest) SetKeyID(keyID string) {
	r.KeyID = keyID
	r.require(revokeSdkKeyRequestFieldKeyID)
}

var (
	createdSdkKeyFieldCreatedAt  = big.NewInt(1 << 0)
	createdSdkKeyFieldID         = big.NewInt(1 << 1)
	createdSdkKeyFieldLastUsedAt = big.NewInt(1 << 2)
	createdSdkKeyFieldName       = big.NewInt(1 << 3)
	createdSdkKeyFieldPrefix     = big.NewInt(1 << 4)
	createdSdkKeyFieldRevokedAt  = big.NewInt(1 << 5)
	createdSdkKeyFieldScopes     = big.NewInt(1 << 6)
	createdSdkKeyFieldTenantID   = big.NewInt(1 << 7)
	createdSdkKeyFieldBearer     = big.NewInt(1 << 8)
)

type CreatedSdkKey struct {
	CreatedAt  time.Time  `json:"createdAt" url:"createdAt"`
	ID         string     `json:"id" url:"id"`
	LastUsedAt *time.Time `json:"lastUsedAt,omitempty" url:"lastUsedAt,omitempty"`
	Name       string     `json:"name" url:"name"`
	Prefix     string     `json:"prefix" url:"prefix"`
	RevokedAt  *time.Time `json:"revokedAt,omitempty" url:"revokedAt,omitempty"`
	Scopes     []string   `json:"scopes" url:"scopes"`
	TenantID   string     `json:"tenantId" url:"tenantId"`
	// One-time plaintext SDK bearer token.
	Bearer string `json:"bearer" url:"bearer"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreatedSdkKey) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *CreatedSdkKey) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreatedSdkKey) GetLastUsedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.LastUsedAt
}

func (c *CreatedSdkKey) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreatedSdkKey) GetPrefix() string {
	if c == nil {
		return ""
	}
	return c.Prefix
}

func (c *CreatedSdkKey) GetRevokedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.RevokedAt
}

func (c *CreatedSdkKey) GetScopes() []string {
	if c == nil {
		return nil
	}
	return c.Scopes
}

func (c *CreatedSdkKey) GetTenantID() string {
	if c == nil {
		return ""
	}
	return c.TenantID
}

func (c *CreatedSdkKey) GetBearer() string {
	if c == nil {
		return ""
	}
	return c.Bearer
}

func (c *CreatedSdkKey) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreatedSdkKey) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatedSdkKey) SetCreatedAt(createdAt time.Time) {
	c.CreatedAt = createdAt
	c.require(createdSdkKeyFieldCreatedAt)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatedSdkKey) SetID(id string) {
	c.ID = id
	c.require(createdSdkKeyFieldID)
}

// SetLastUsedAt sets the LastUsedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatedSdkKey) SetLastUsedAt(lastUsedAt *time.Time) {
	c.LastUsedAt = lastUsedAt
	c.require(createdSdkKeyFieldLastUsedAt)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatedSdkKey) SetName(name string) {
	c.Name = name
	c.require(createdSdkKeyFieldName)
}

// SetPrefix sets the Prefix field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatedSdkKey) SetPrefix(prefix string) {
	c.Prefix = prefix
	c.require(createdSdkKeyFieldPrefix)
}

// SetRevokedAt sets the RevokedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatedSdkKey) SetRevokedAt(revokedAt *time.Time) {
	c.RevokedAt = revokedAt
	c.require(createdSdkKeyFieldRevokedAt)
}

// SetScopes sets the Scopes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatedSdkKey) SetScopes(scopes []string) {
	c.Scopes = scopes
	c.require(createdSdkKeyFieldScopes)
}

// SetTenantID sets the TenantID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatedSdkKey) SetTenantID(tenantID string) {
	c.TenantID = tenantID
	c.require(createdSdkKeyFieldTenantID)
}

// SetBearer sets the Bearer field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatedSdkKey) SetBearer(bearer string) {
	c.Bearer = bearer
	c.require(createdSdkKeyFieldBearer)
}

func (c *CreatedSdkKey) UnmarshalJSON(data []byte) error {
	type embed CreatedSdkKey
	var unmarshaler = struct {
		embed
		CreatedAt  *internal.DateTime `json:"createdAt"`
		LastUsedAt *internal.DateTime `json:"lastUsedAt,omitempty"`
		RevokedAt  *internal.DateTime `json:"revokedAt,omitempty"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CreatedSdkKey(unmarshaler.embed)
	c.CreatedAt = unmarshaler.CreatedAt.Time()
	c.LastUsedAt = unmarshaler.LastUsedAt.TimePtr()
	c.RevokedAt = unmarshaler.RevokedAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreatedSdkKey) MarshalJSON() ([]byte, error) {
	type embed CreatedSdkKey
	var marshaler = struct {
		embed
		CreatedAt  *internal.DateTime `json:"createdAt"`
		LastUsedAt *internal.DateTime `json:"lastUsedAt,omitempty"`
		RevokedAt  *internal.DateTime `json:"revokedAt,omitempty"`
	}{
		embed:      embed(*c),
		CreatedAt:  internal.NewDateTime(c.CreatedAt),
		LastUsedAt: internal.NewOptionalDateTime(c.LastUsedAt),
		RevokedAt:  internal.NewOptionalDateTime(c.RevokedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreatedSdkKey) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	sdkKeyFieldCreatedAt  = big.NewInt(1 << 0)
	sdkKeyFieldID         = big.NewInt(1 << 1)
	sdkKeyFieldLastUsedAt = big.NewInt(1 << 2)
	sdkKeyFieldName       = big.NewInt(1 << 3)
	sdkKeyFieldPrefix     = big.NewInt(1 << 4)
	sdkKeyFieldRevokedAt  = big.NewInt(1 << 5)
	sdkKeyFieldScopes     = big.NewInt(1 << 6)
	sdkKeyFieldTenantID   = big.NewInt(1 << 7)
)

type SdkKey struct {
	CreatedAt  time.Time  `json:"createdAt" url:"createdAt"`
	ID         string     `json:"id" url:"id"`
	LastUsedAt *time.Time `json:"lastUsedAt,omitempty" url:"lastUsedAt,omitempty"`
	Name       string     `json:"name" url:"name"`
	Prefix     string     `json:"prefix" url:"prefix"`
	RevokedAt  *time.Time `json:"revokedAt,omitempty" url:"revokedAt,omitempty"`
	Scopes     []string   `json:"scopes" url:"scopes"`
	TenantID   string     `json:"tenantId" url:"tenantId"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SdkKey) GetCreatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CreatedAt
}

func (s *SdkKey) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SdkKey) GetLastUsedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.LastUsedAt
}

func (s *SdkKey) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *SdkKey) GetPrefix() string {
	if s == nil {
		return ""
	}
	return s.Prefix
}

func (s *SdkKey) GetRevokedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.RevokedAt
}

func (s *SdkKey) GetScopes() []string {
	if s == nil {
		return nil
	}
	return s.Scopes
}

func (s *SdkKey) GetTenantID() string {
	if s == nil {
		return ""
	}
	return s.TenantID
}

func (s *SdkKey) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SdkKey) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SdkKey) SetCreatedAt(createdAt time.Time) {
	s.CreatedAt = createdAt
	s.require(sdkKeyFieldCreatedAt)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SdkKey) SetID(id string) {
	s.ID = id
	s.require(sdkKeyFieldID)
}

// SetLastUsedAt sets the LastUsedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SdkKey) SetLastUsedAt(lastUsedAt *time.Time) {
	s.LastUsedAt = lastUsedAt
	s.require(sdkKeyFieldLastUsedAt)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SdkKey) SetName(name string) {
	s.Name = name
	s.require(sdkKeyFieldName)
}

// SetPrefix sets the Prefix field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SdkKey) SetPrefix(prefix string) {
	s.Prefix = prefix
	s.require(sdkKeyFieldPrefix)
}

// SetRevokedAt sets the RevokedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SdkKey) SetRevokedAt(revokedAt *time.Time) {
	s.RevokedAt = revokedAt
	s.require(sdkKeyFieldRevokedAt)
}

// SetScopes sets the Scopes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SdkKey) SetScopes(scopes []string) {
	s.Scopes = scopes
	s.require(sdkKeyFieldScopes)
}

// SetTenantID sets the TenantID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SdkKey) SetTenantID(tenantID string) {
	s.TenantID = tenantID
	s.require(sdkKeyFieldTenantID)
}

func (s *SdkKey) UnmarshalJSON(data []byte) error {
	type embed SdkKey
	var unmarshaler = struct {
		embed
		CreatedAt  *internal.DateTime `json:"createdAt"`
		LastUsedAt *internal.DateTime `json:"lastUsedAt,omitempty"`
		RevokedAt  *internal.DateTime `json:"revokedAt,omitempty"`
	}{
		embed: embed(*s),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*s = SdkKey(unmarshaler.embed)
	s.CreatedAt = unmarshaler.CreatedAt.Time()
	s.LastUsedAt = unmarshaler.LastUsedAt.TimePtr()
	s.RevokedAt = unmarshaler.RevokedAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SdkKey) MarshalJSON() ([]byte, error) {
	type embed SdkKey
	var marshaler = struct {
		embed
		CreatedAt  *internal.DateTime `json:"createdAt"`
		LastUsedAt *internal.DateTime `json:"lastUsedAt,omitempty"`
		RevokedAt  *internal.DateTime `json:"revokedAt,omitempty"`
	}{
		embed:      embed(*s),
		CreatedAt:  internal.NewDateTime(s.CreatedAt),
		LastUsedAt: internal.NewOptionalDateTime(s.LastUsedAt),
		RevokedAt:  internal.NewOptionalDateTime(s.RevokedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SdkKey) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	sdkKeyListResponseFieldKeys = big.NewInt(1 << 0)
)

type SdkKeyListResponse struct {
	Keys []*SdkKey `json:"keys" url:"keys"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SdkKeyListResponse) GetKeys() []*SdkKey {
	if s == nil {
		return nil
	}
	return s.Keys
}

func (s *SdkKeyListResponse) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SdkKeyListResponse) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetKeys sets the Keys field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SdkKeyListResponse) SetKeys(keys []*SdkKey) {
	s.Keys = keys
	s.require(sdkKeyListResponseFieldKeys)
}

func (s *SdkKeyListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler SdkKeyListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SdkKeyListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SdkKeyListResponse) MarshalJSON() ([]byte, error) {
	type embed SdkKeyListResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SdkKeyListResponse) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type CreateSdkKeyRequestScopesItem string

const (
	CreateSdkKeyRequestScopesItemTracesWrite  CreateSdkKeyRequestScopesItem = "traces:write"
	CreateSdkKeyRequestScopesItemEventsRead   CreateSdkKeyRequestScopesItem = "events:read"
	CreateSdkKeyRequestScopesItemEventsWrite  CreateSdkKeyRequestScopesItem = "events:write"
	CreateSdkKeyRequestScopesItemUsersWrite   CreateSdkKeyRequestScopesItem = "users:write"
	CreateSdkKeyRequestScopesItemSignalsWrite CreateSdkKeyRequestScopesItem = "signals:write"
	CreateSdkKeyRequestScopesItemAgentsWrite  CreateSdkKeyRequestScopesItem = "agents:write"
)

func NewCreateSdkKeyRequestScopesItemFromString(s string) (CreateSdkKeyRequestScopesItem, error) {
	switch s {
	case "traces:write":
		return CreateSdkKeyRequestScopesItemTracesWrite, nil
	case "events:read":
		return CreateSdkKeyRequestScopesItemEventsRead, nil
	case "events:write":
		return CreateSdkKeyRequestScopesItemEventsWrite, nil
	case "users:write":
		return CreateSdkKeyRequestScopesItemUsersWrite, nil
	case "signals:write":
		return CreateSdkKeyRequestScopesItemSignalsWrite, nil
	case "agents:write":
		return CreateSdkKeyRequestScopesItemAgentsWrite, nil
	}
	var t CreateSdkKeyRequestScopesItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateSdkKeyRequestScopesItem) Ptr() *CreateSdkKeyRequestScopesItem {
	return &c
}
