// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/chronicle-labs-ai/chronicle-go/internal"
	big "math/big"
	time "time"
)

var (
	getEventSchemaRequestFieldSource    = big.NewInt(1 << 0)
	getEventSchemaRequestFieldEventType = big.NewInt(1 << 1)
)

type GetEventSchemaRequest struct {
	Source    string `json:"-" url:"-"`
	EventType string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetEventSchemaRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetSource sets the Source field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetEventSchemaRequest) SetSource(source string) {
	g.Source = source
	g.require(getEventSchemaRequestFieldSource)
}

// SetEventType sets the EventType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetEventSchemaRequest) SetEventType(eventType string) {
	g.EventType = eventType
	g.require(getEventSchemaRequestFieldEventType)
}

var (
	listEntitiesRequestFieldEntityType = big.NewInt(1 << 0)
	listEntitiesRequestFieldLimit      = big.NewInt(1 << 1)
	listEntitiesRequestFieldCursor     = big.NewInt(1 << 2)
)

type ListEntitiesRequest struct {
	EntityType string `json:"-" url:"-"`
	// Page size. Values above 200 are clamped to 200.
	Limit *int `json:"-" url:"limit,omitempty"`
	// Opaque position returned as `next_cursor` by the preceding page.
	Cursor *string `json:"-" url:"cursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListEntitiesRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetEntityType sets the EntityType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListEntitiesRequest) SetEntityType(entityType string) {
	l.EntityType = entityType
	l.require(listEntitiesRequestFieldEntityType)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListEntitiesRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listEntitiesRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListEntitiesRequest) SetCursor(cursor *string) {
	l.Cursor = cursor
	l.require(listEntitiesRequestFieldCursor)
}

// A single entity and its event volume.
var (
	entityInfoFieldEntityType = big.NewInt(1 << 0)
	entityInfoFieldEntityID   = big.NewInt(1 << 1)
	entityInfoFieldEventCount = big.NewInt(1 << 2)
	entityInfoFieldFirstSeen  = big.NewInt(1 << 3)
	entityInfoFieldLastSeen   = big.NewInt(1 << 4)
)

type EntityInfo struct {
	EntityType string     `json:"entity_type" url:"entity_type"`
	EntityID   string     `json:"entity_id" url:"entity_id"`
	EventCount int64      `json:"event_count" url:"event_count"`
	FirstSeen  *time.Time `json:"first_seen,omitempty" url:"first_seen,omitempty"`
	LastSeen   *time.Time `json:"last_seen,omitempty" url:"last_seen,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EntityInfo) GetEntityType() string {
	if e == nil {
		return ""
	}
	return e.EntityType
}

func (e *EntityInfo) GetEntityID() string {
	if e == nil {
		return ""
	}
	return e.EntityID
}

func (e *EntityInfo) GetEventCount() int64 {
	if e == nil {
		return 0
	}
	return e.EventCount
}

func (e *EntityInfo) GetFirstSeen() *time.Time {
	if e == nil {
		return nil
	}
	return e.FirstSeen
}

func (e *EntityInfo) GetLastSeen() *time.Time {
	if e == nil {
		return nil
	}
	return e.LastSeen
}

func (e *EntityInfo) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *EntityInfo) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetEntityType sets the EntityType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityInfo) SetEntityType(entityType string) {
	e.EntityType = entityType
	e.require(entityInfoFieldEntityType)
}

// SetEntityID sets the EntityID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityInfo) SetEntityID(entityID string) {
	e.EntityID = entityID
	e.require(entityInfoFieldEntityID)
}

// SetEventCount sets the EventCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityInfo) SetEventCount(eventCount int64) {
	e.EventCount = eventCount
	e.require(entityInfoFieldEventCount)
}

// SetFirstSeen sets the FirstSeen field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityInfo) SetFirstSeen(firstSeen *time.Time) {
	e.FirstSeen = firstSeen
	e.require(entityInfoFieldFirstSeen)
}

// SetLastSeen sets the LastSeen field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityInfo) SetLastSeen(lastSeen *time.Time) {
	e.LastSeen = lastSeen
	e.require(entityInfoFieldLastSeen)
}

func (e *EntityInfo) UnmarshalJSON(data []byte) error {
	type embed EntityInfo
	var unmarshaler = struct {
		embed
		FirstSeen *internal.DateTime `json:"first_seen,omitempty"`
		LastSeen  *internal.DateTime `json:"last_seen,omitempty"`
	}{
		embed: embed(*e),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*e = EntityInfo(unmarshaler.embed)
	e.FirstSeen = unmarshaler.FirstSeen.TimePtr()
	e.LastSeen = unmarshaler.LastSeen.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EntityInfo) MarshalJSON() ([]byte, error) {
	type embed EntityInfo
	var marshaler = struct {
		embed
		FirstSeen *internal.DateTime `json:"first_seen,omitempty"`
		LastSeen  *internal.DateTime `json:"last_seen,omitempty"`
	}{
		embed:     embed(*e),
		FirstSeen: internal.NewOptionalDateTime(e.FirstSeen),
		LastSeen:  internal.NewOptionalDateTime(e.LastSeen),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EntityInfo) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

// A stable page ordered by event count and entity ID.
var (
	entityListResponseFieldData       = big.NewInt(1 << 0)
	entityListResponseFieldNextCursor = big.NewInt(1 << 1)
)

type EntityListResponse struct {
	Data []*EntityInfo `json:"data" url:"data"`
	// Opaque position for the next request.
	NextCursor *string `json:"next_cursor,omitempty" url:"next_cursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EntityListResponse) GetData() []*EntityInfo {
	if e == nil {
		return nil
	}
	return e.Data
}

func (e *EntityListResponse) GetNextCursor() *string {
	if e == nil {
		return nil
	}
	return e.NextCursor
}

func (e *EntityListResponse) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *EntityListResponse) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityListResponse) SetData(data []*EntityInfo) {
	e.Data = data
	e.require(entityListResponseFieldData)
}

// SetNextCursor sets the NextCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityListResponse) SetNextCursor(nextCursor *string) {
	e.NextCursor = nextCursor
	e.require(entityListResponseFieldNextCursor)
}

func (e *EntityListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler EntityListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EntityListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EntityListResponse) MarshalJSON() ([]byte, error) {
	type embed EntityListResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EntityListResponse) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

// An entity type in use and how much of it there is.
var (
	entityTypeInfoFieldEntityType  = big.NewInt(1 << 0)
	entityTypeInfoFieldEntityCount = big.NewInt(1 << 1)
	entityTypeInfoFieldFirstSeen   = big.NewInt(1 << 2)
	entityTypeInfoFieldLastSeen    = big.NewInt(1 << 3)
)

type EntityTypeInfo struct {
	EntityType  string     `json:"entity_type" url:"entity_type"`
	EntityCount int64      `json:"entity_count" url:"entity_count"`
	FirstSeen   *time.Time `json:"first_seen,omitempty" url:"first_seen,omitempty"`
	LastSeen    *time.Time `json:"last_seen,omitempty" url:"last_seen,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EntityTypeInfo) GetEntityType() string {
	if e == nil {
		return ""
	}
	return e.EntityType
}

func (e *EntityTypeInfo) GetEntityCount() int64 {
	if e == nil {
		return 0
	}
	return e.EntityCount
}

func (e *EntityTypeInfo) GetFirstSeen() *time.Time {
	if e == nil {
		return nil
	}
	return e.FirstSeen
}

func (e *EntityTypeInfo) GetLastSeen() *time.Time {
	if e == nil {
		return nil
	}
	return e.LastSeen
}

func (e *EntityTypeInfo) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *EntityTypeInfo) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetEntityType sets the EntityType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityTypeInfo) SetEntityType(entityType string) {
	e.EntityType = entityType
	e.require(entityTypeInfoFieldEntityType)
}

// SetEntityCount sets the EntityCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityTypeInfo) SetEntityCount(entityCount int64) {
	e.EntityCount = entityCount
	e.require(entityTypeInfoFieldEntityCount)
}

// SetFirstSeen sets the FirstSeen field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityTypeInfo) SetFirstSeen(firstSeen *time.Time) {
	e.FirstSeen = firstSeen
	e.require(entityTypeInfoFieldFirstSeen)
}

// SetLastSeen sets the LastSeen field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityTypeInfo) SetLastSeen(lastSeen *time.Time) {
	e.LastSeen = lastSeen
	e.require(entityTypeInfoFieldLastSeen)
}

func (e *EntityTypeInfo) UnmarshalJSON(data []byte) error {
	type embed EntityTypeInfo
	var unmarshaler = struct {
		embed
		FirstSeen *internal.DateTime `json:"first_seen,omitempty"`
		LastSeen  *internal.DateTime `json:"last_seen,omitempty"`
	}{
		embed: embed(*e),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*e = EntityTypeInfo(unmarshaler.embed)
	e.FirstSeen = unmarshaler.FirstSeen.TimePtr()
	e.LastSeen = unmarshaler.LastSeen.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EntityTypeInfo) MarshalJSON() ([]byte, error) {
	type embed EntityTypeInfo
	var marshaler = struct {
		embed
		FirstSeen *internal.DateTime `json:"first_seen,omitempty"`
		LastSeen  *internal.DateTime `json:"last_seen,omitempty"`
	}{
		embed:     embed(*e),
		FirstSeen: internal.NewOptionalDateTime(e.FirstSeen),
		LastSeen:  internal.NewOptionalDateTime(e.LastSeen),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EntityTypeInfo) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

var (
	entityTypeListResponseFieldData       = big.NewInt(1 << 0)
	entityTypeListResponseFieldNextCursor = big.NewInt(1 << 1)
)

type EntityTypeListResponse struct {
	Data       []*EntityTypeInfo `json:"data" url:"data"`
	NextCursor *string           `json:"next_cursor,omitempty" url:"next_cursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EntityTypeListResponse) GetData() []*EntityTypeInfo {
	if e == nil {
		return nil
	}
	return e.Data
}

func (e *EntityTypeListResponse) GetNextCursor() *string {
	if e == nil {
		return nil
	}
	return e.NextCursor
}

func (e *EntityTypeListResponse) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *EntityTypeListResponse) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityTypeListResponse) SetData(data []*EntityTypeInfo) {
	e.Data = data
	e.require(entityTypeListResponseFieldData)
}

// SetNextCursor sets the NextCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityTypeListResponse) SetNextCursor(nextCursor *string) {
	e.NextCursor = nextCursor
	e.require(entityTypeListResponseFieldNextCursor)
}

func (e *EntityTypeListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler EntityTypeListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EntityTypeListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EntityTypeListResponse) MarshalJSON() ([]byte, error) {
	type embed EntityTypeListResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EntityTypeListResponse) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

// A connected source and what has been seen from it.
var (
	sourceInfoFieldSource     = big.NewInt(1 << 0)
	sourceInfoFieldEventTypes = big.NewInt(1 << 1)
	sourceInfoFieldEventCount = big.NewInt(1 << 2)
	sourceInfoFieldFirstSeen  = big.NewInt(1 << 3)
	sourceInfoFieldLastSeen   = big.NewInt(1 << 4)
)

type SourceInfo struct {
	Source     string     `json:"source" url:"source"`
	EventTypes []string   `json:"event_types" url:"event_types"`
	EventCount int64      `json:"event_count" url:"event_count"`
	FirstSeen  *time.Time `json:"first_seen,omitempty" url:"first_seen,omitempty"`
	LastSeen   *time.Time `json:"last_seen,omitempty" url:"last_seen,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SourceInfo) GetSource() string {
	if s == nil {
		return ""
	}
	return s.Source
}

func (s *SourceInfo) GetEventTypes() []string {
	if s == nil {
		return nil
	}
	return s.EventTypes
}

func (s *SourceInfo) GetEventCount() int64 {
	if s == nil {
		return 0
	}
	return s.EventCount
}

func (s *SourceInfo) GetFirstSeen() *time.Time {
	if s == nil {
		return nil
	}
	return s.FirstSeen
}

func (s *SourceInfo) GetLastSeen() *time.Time {
	if s == nil {
		return nil
	}
	return s.LastSeen
}

func (s *SourceInfo) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SourceInfo) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetSource sets the Source field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SourceInfo) SetSource(source string) {
	s.Source = source
	s.require(sourceInfoFieldSource)
}

// SetEventTypes sets the EventTypes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SourceInfo) SetEventTypes(eventTypes []string) {
	s.EventTypes = eventTypes
	s.require(sourceInfoFieldEventTypes)
}

// SetEventCount sets the EventCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SourceInfo) SetEventCount(eventCount int64) {
	s.EventCount = eventCount
	s.require(sourceInfoFieldEventCount)
}

// SetFirstSeen sets the FirstSeen field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SourceInfo) SetFirstSeen(firstSeen *time.Time) {
	s.FirstSeen = firstSeen
	s.require(sourceInfoFieldFirstSeen)
}

// SetLastSeen sets the LastSeen field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SourceInfo) SetLastSeen(lastSeen *time.Time) {
	s.LastSeen = lastSeen
	s.require(sourceInfoFieldLastSeen)
}

func (s *SourceInfo) UnmarshalJSON(data []byte) error {
	type embed SourceInfo
	var unmarshaler = struct {
		embed
		FirstSeen *internal.DateTime `json:"first_seen,omitempty"`
		LastSeen  *internal.DateTime `json:"last_seen,omitempty"`
	}{
		embed: embed(*s),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*s = SourceInfo(unmarshaler.embed)
	s.FirstSeen = unmarshaler.FirstSeen.TimePtr()
	s.LastSeen = unmarshaler.LastSeen.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SourceInfo) MarshalJSON() ([]byte, error) {
	type embed SourceInfo
	var marshaler = struct {
		embed
		FirstSeen *internal.DateTime `json:"first_seen,omitempty"`
		LastSeen  *internal.DateTime `json:"last_seen,omitempty"`
	}{
		embed:     embed(*s),
		FirstSeen: internal.NewOptionalDateTime(s.FirstSeen),
		LastSeen:  internal.NewOptionalDateTime(s.LastSeen),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SourceInfo) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	sourceListResponseFieldData       = big.NewInt(1 << 0)
	sourceListResponseFieldNextCursor = big.NewInt(1 << 1)
)

type SourceListResponse struct {
	Data       []*SourceInfo `json:"data" url:"data"`
	NextCursor *string       `json:"next_cursor,omitempty" url:"next_cursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SourceListResponse) GetData() []*SourceInfo {
	if s == nil {
		return nil
	}
	return s.Data
}

func (s *SourceListResponse) GetNextCursor() *string {
	if s == nil {
		return nil
	}
	return s.NextCursor
}

func (s *SourceListResponse) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SourceListResponse) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SourceListResponse) SetData(data []*SourceInfo) {
	s.Data = data
	s.require(sourceListResponseFieldData)
}

// SetNextCursor sets the NextCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SourceListResponse) SetNextCursor(nextCursor *string) {
	s.NextCursor = nextCursor
	s.require(sourceListResponseFieldNextCursor)
}

func (s *SourceListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler SourceListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SourceListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SourceListResponse) MarshalJSON() ([]byte, error) {
	type embed SourceListResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SourceListResponse) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

// The inferred payload shape for one source and event type.
var (
	sourceSchemaFieldOrgID       = big.NewInt(1 << 0)
	sourceSchemaFieldSource      = big.NewInt(1 << 1)
	sourceSchemaFieldEventType   = big.NewInt(1 << 2)
	sourceSchemaFieldVersion     = big.NewInt(1 << 3)
	sourceSchemaFieldFieldNames  = big.NewInt(1 << 4)
	sourceSchemaFieldFieldTypes  = big.NewInt(1 << 5)
	sourceSchemaFieldSampleEvent = big.NewInt(1 << 6)
)

type SourceSchema struct {
	OrgID     string `json:"org_id" url:"org_id"`
	Source    string `json:"source" url:"source"`
	EventType string `json:"event_type" url:"event_type"`
	// Bumped when the inferred shape changes.
	Version     int            `json:"version" url:"version"`
	FieldNames  []string       `json:"field_names" url:"field_names"`
	FieldTypes  []string       `json:"field_types" url:"field_types"`
	SampleEvent map[string]any `json:"sample_event,omitempty" url:"sample_event,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SourceSchema) GetOrgID() string {
	if s == nil {
		return ""
	}
	return s.OrgID
}

func (s *SourceSchema) GetSource() string {
	if s == nil {
		return ""
	}
	return s.Source
}

func (s *SourceSchema) GetEventType() string {
	if s == nil {
		return ""
	}
	return s.EventType
}

func (s *SourceSchema) GetVersion() int {
	if s == nil {
		return 0
	}
	return s.Version
}

func (s *SourceSchema) GetFieldNames() []string {
	if s == nil {
		return nil
	}
	return s.FieldNames
}

func (s *SourceSchema) GetFieldTypes() []string {
	if s == nil {
		return nil
	}
	return s.FieldTypes
}

func (s *SourceSchema) GetSampleEvent() map[string]any {
	if s == nil {
		return nil
	}
	return s.SampleEvent
}

func (s *SourceSchema) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SourceSchema) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetOrgID sets the OrgID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SourceSchema) SetOrgID(orgID string) {
	s.OrgID = orgID
	s.require(sourceSchemaFieldOrgID)
}

// SetSource sets the Source field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SourceSchema) SetSource(source string) {
	s.Source = source
	s.require(sourceSchemaFieldSource)
}

// SetEventType sets the EventType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SourceSchema) SetEventType(eventType string) {
	s.EventType = eventType
	s.require(sourceSchemaFieldEventType)
}

// SetVersion sets the Version field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SourceSchema) SetVersion(version int) {
	s.Version = version
	s.require(sourceSchemaFieldVersion)
}

// SetFieldNames sets the FieldNames field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SourceSchema) SetFieldNames(fieldNames []string) {
	s.FieldNames = fieldNames
	s.require(sourceSchemaFieldFieldNames)
}

// SetFieldTypes sets the FieldTypes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SourceSchema) SetFieldTypes(fieldTypes []string) {
	s.FieldTypes = fieldTypes
	s.require(sourceSchemaFieldFieldTypes)
}

// SetSampleEvent sets the SampleEvent field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SourceSchema) SetSampleEvent(sampleEvent map[string]any) {
	s.SampleEvent = sampleEvent
	s.require(sourceSchemaFieldSampleEvent)
}

func (s *SourceSchema) UnmarshalJSON(data []byte) error {
	type unmarshaler SourceSchema
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SourceSchema(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SourceSchema) MarshalJSON() ([]byte, error) {
	type embed SourceSchema
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SourceSchema) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}
