// Code generated by Fern. DO NOT EDIT.

package api

import (
	core "github.com/chronicle-labs-ai/chronicle-go/core"
	internal "github.com/chronicle-labs-ai/chronicle-go/internal"
)

var ErrorCodes internal.ErrorCodes = internal.ErrorCodes{
	400: func(apiError *core.APIError) error {
		return &BadRequestError{
			APIError: apiError,
		}
	},
	401: func(apiError *core.APIError) error {
		return &UnauthorizedError{
			APIError: apiError,
		}
	},
	429: func(apiError *core.APIError) error {
		return &TooManyRequestsError{
			APIError: apiError,
		}
	},
	500: func(apiError *core.APIError) error {
		return &InternalServerError{
			APIError: apiError,
		}
	},
	503: func(apiError *core.APIError) error {
		return &ServiceUnavailableError{
			APIError: apiError,
		}
	},
	504: func(apiError *core.APIError) error {
		return &GatewayTimeoutError{
			APIError: apiError,
		}
	},
	413: func(apiError *core.APIError) error {
		return &ContentTooLargeError{
			APIError: apiError,
		}
	},
	415: func(apiError *core.APIError) error {
		return &UnsupportedMediaTypeError{
			APIError: apiError,
		}
	},
	422: func(apiError *core.APIError) error {
		return &UnprocessableEntityError{
			APIError: apiError,
		}
	},
	409: func(apiError *core.APIError) error {
		return &ConflictError{
			APIError: apiError,
		}
	},
	404: func(apiError *core.APIError) error {
		return &NotFoundError{
			APIError: apiError,
		}
	},
}
