// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/chronicle-labs-ai/chronicle-go/internal"
	big "math/big"
)

var (
	addEntityRefRequestFieldEventID    = big.NewInt(1 << 0)
	addEntityRefRequestFieldEntityType = big.NewInt(1 << 1)
	addEntityRefRequestFieldEntityID   = big.NewInt(1 << 2)
	addEntityRefRequestFieldCreatedBy  = big.NewInt(1 << 3)
)

type AddEntityRefRequest struct {
	EventID    string  `json:"event_id" url:"-"`
	EntityType string  `json:"entity_type" url:"-"`
	EntityID   string  `json:"entity_id" url:"-"`
	CreatedBy  *string `json:"created_by,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AddEntityRefRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetEventID sets the EventID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddEntityRefRequest) SetEventID(eventID string) {
	a.EventID = eventID
	a.require(addEntityRefRequestFieldEventID)
}

// SetEntityType sets the EntityType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddEntityRefRequest) SetEntityType(entityType string) {
	a.EntityType = entityType
	a.require(addEntityRefRequestFieldEntityType)
}

// SetEntityID sets the EntityID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddEntityRefRequest) SetEntityID(entityID string) {
	a.EntityID = entityID
	a.require(addEntityRefRequestFieldEntityID)
}

// SetCreatedBy sets the CreatedBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddEntityRefRequest) SetCreatedBy(createdBy *string) {
	a.CreatedBy = createdBy
	a.require(addEntityRefRequestFieldCreatedBy)
}

func (a *AddEntityRefRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler AddEntityRefRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*a = AddEntityRefRequest(body)
	return nil
}

func (a *AddEntityRefRequest) MarshalJSON() ([]byte, error) {
	type embed AddEntityRefRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	createLinkRequestFieldSourceEventID = big.NewInt(1 << 0)
	createLinkRequestFieldTargetEventID = big.NewInt(1 << 1)
	createLinkRequestFieldLinkType      = big.NewInt(1 << 2)
	createLinkRequestFieldConfidence    = big.NewInt(1 << 3)
	createLinkRequestFieldReasoning     = big.NewInt(1 << 4)
	createLinkRequestFieldCreatedBy     = big.NewInt(1 << 5)
)

type CreateLinkRequest struct {
	SourceEventID string  `json:"source_event_id" url:"-"`
	TargetEventID string  `json:"target_event_id" url:"-"`
	LinkType      string  `json:"link_type" url:"-"`
	Confidence    float64 `json:"confidence" url:"-"`
	Reasoning     *string `json:"reasoning,omitempty" url:"-"`
	CreatedBy     *string `json:"created_by,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateLinkRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetSourceEventID sets the SourceEventID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateLinkRequest) SetSourceEventID(sourceEventID string) {
	c.SourceEventID = sourceEventID
	c.require(createLinkRequestFieldSourceEventID)
}

// SetTargetEventID sets the TargetEventID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateLinkRequest) SetTargetEventID(targetEventID string) {
	c.TargetEventID = targetEventID
	c.require(createLinkRequestFieldTargetEventID)
}

// SetLinkType sets the LinkType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateLinkRequest) SetLinkType(linkType string) {
	c.LinkType = linkType
	c.require(createLinkRequestFieldLinkType)
}

// SetConfidence sets the Confidence field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateLinkRequest) SetConfidence(confidence float64) {
	c.Confidence = confidence
	c.require(createLinkRequestFieldConfidence)
}

// SetReasoning sets the Reasoning field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateLinkRequest) SetReasoning(reasoning *string) {
	c.Reasoning = reasoning
	c.require(createLinkRequestFieldReasoning)
}

// SetCreatedBy sets the CreatedBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateLinkRequest) SetCreatedBy(createdBy *string) {
	c.CreatedBy = createdBy
	c.require(createLinkRequestFieldCreatedBy)
}

func (c *CreateLinkRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateLinkRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateLinkRequest(body)
	return nil
}

func (c *CreateLinkRequest) MarshalJSON() ([]byte, error) {
	type embed CreateLinkRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	linkEntityRequestFieldFromEntityType = big.NewInt(1 << 0)
	linkEntityRequestFieldFromEntityID   = big.NewInt(1 << 1)
	linkEntityRequestFieldToEntityType   = big.NewInt(1 << 2)
	linkEntityRequestFieldToEntityID     = big.NewInt(1 << 3)
	linkEntityRequestFieldCreatedBy      = big.NewInt(1 << 4)
)

type LinkEntityRequest struct {
	FromEntityType string  `json:"from_entity_type" url:"-"`
	FromEntityID   string  `json:"from_entity_id" url:"-"`
	ToEntityType   string  `json:"to_entity_type" url:"-"`
	ToEntityID     string  `json:"to_entity_id" url:"-"`
	CreatedBy      *string `json:"created_by,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *LinkEntityRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetFromEntityType sets the FromEntityType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LinkEntityRequest) SetFromEntityType(fromEntityType string) {
	l.FromEntityType = fromEntityType
	l.require(linkEntityRequestFieldFromEntityType)
}

// SetFromEntityID sets the FromEntityID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LinkEntityRequest) SetFromEntityID(fromEntityID string) {
	l.FromEntityID = fromEntityID
	l.require(linkEntityRequestFieldFromEntityID)
}

// SetToEntityType sets the ToEntityType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LinkEntityRequest) SetToEntityType(toEntityType string) {
	l.ToEntityType = toEntityType
	l.require(linkEntityRequestFieldToEntityType)
}

// SetToEntityID sets the ToEntityID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LinkEntityRequest) SetToEntityID(toEntityID string) {
	l.ToEntityID = toEntityID
	l.require(linkEntityRequestFieldToEntityID)
}

// SetCreatedBy sets the CreatedBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LinkEntityRequest) SetCreatedBy(createdBy *string) {
	l.CreatedBy = createdBy
	l.require(linkEntityRequestFieldCreatedBy)
}

func (l *LinkEntityRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler LinkEntityRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*l = LinkEntityRequest(body)
	return nil
}

func (l *LinkEntityRequest) MarshalJSON() ([]byte, error) {
	type embed LinkEntityRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	graphRequestFieldStartEventID  = big.NewInt(1 << 0)
	graphRequestFieldDirection     = big.NewInt(1 << 1)
	graphRequestFieldLinkTypes     = big.NewInt(1 << 2)
	graphRequestFieldMaxDepth      = big.NewInt(1 << 3)
	graphRequestFieldMinConfidence = big.NewInt(1 << 4)
)

type GraphRequest struct {
	StartEventID  string                `json:"start_event_id" url:"-"`
	Direction     GraphRequestDirection `json:"direction" url:"-"`
	LinkTypes     []string              `json:"link_types,omitempty" url:"-"`
	MaxDepth      *int                  `json:"max_depth,omitempty" url:"-"`
	MinConfidence *float64              `json:"min_confidence,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GraphRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetStartEventID sets the StartEventID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GraphRequest) SetStartEventID(startEventID string) {
	g.StartEventID = startEventID
	g.require(graphRequestFieldStartEventID)
}

// SetDirection sets the Direction field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GraphRequest) SetDirection(direction GraphRequestDirection) {
	g.Direction = direction
	g.require(graphRequestFieldDirection)
}

// SetLinkTypes sets the LinkTypes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GraphRequest) SetLinkTypes(linkTypes []string) {
	g.LinkTypes = linkTypes
	g.require(graphRequestFieldLinkTypes)
}

// SetMaxDepth sets the MaxDepth field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GraphRequest) SetMaxDepth(maxDepth *int) {
	g.MaxDepth = maxDepth
	g.require(graphRequestFieldMaxDepth)
}

// SetMinConfidence sets the MinConfidence field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GraphRequest) SetMinConfidence(minConfidence *float64) {
	g.MinConfidence = minConfidence
	g.require(graphRequestFieldMinConfidence)
}

func (g *GraphRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler GraphRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*g = GraphRequest(body)
	return nil
}

func (g *GraphRequest) MarshalJSON() ([]byte, error) {
	type embed GraphRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	createLinkResponseFieldLinkID = big.NewInt(1 << 0)
)

type CreateLinkResponse struct {
	LinkID string `json:"link_id" url:"link_id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateLinkResponse) GetLinkID() string {
	if c == nil {
		return ""
	}
	return c.LinkID
}

func (c *CreateLinkResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateLinkResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetLinkID sets the LinkID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateLinkResponse) SetLinkID(linkID string) {
	c.LinkID = linkID
	c.require(createLinkResponseFieldLinkID)
}

func (c *CreateLinkResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateLinkResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateLinkResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateLinkResponse) MarshalJSON() ([]byte, error) {
	type embed CreateLinkResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateLinkResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	linkEntityResponseFieldLinkedCount = big.NewInt(1 << 0)
)

type LinkEntityResponse struct {
	LinkedCount int `json:"linked_count" url:"linked_count"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *LinkEntityResponse) GetLinkedCount() int {
	if l == nil {
		return 0
	}
	return l.LinkedCount
}

func (l *LinkEntityResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *LinkEntityResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetLinkedCount sets the LinkedCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LinkEntityResponse) SetLinkedCount(linkedCount int) {
	l.LinkedCount = linkedCount
	l.require(linkEntityResponseFieldLinkedCount)
}

func (l *LinkEntityResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler LinkEntityResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = LinkEntityResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *LinkEntityResponse) MarshalJSON() ([]byte, error) {
	type embed LinkEntityResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *LinkEntityResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	statusResponseFieldStatus = big.NewInt(1 << 0)
)

type StatusResponse struct {
	Status string `json:"status" url:"status"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *StatusResponse) GetStatus() string {
	if s == nil {
		return ""
	}
	return s.Status
}

func (s *StatusResponse) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *StatusResponse) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StatusResponse) SetStatus(status string) {
	s.Status = status
	s.require(statusResponseFieldStatus)
}

func (s *StatusResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler StatusResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = StatusResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *StatusResponse) MarshalJSON() ([]byte, error) {
	type embed StatusResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *StatusResponse) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type GraphRequestDirection string

const (
	GraphRequestDirectionOutgoing GraphRequestDirection = "outgoing"
	GraphRequestDirectionIncoming GraphRequestDirection = "incoming"
	GraphRequestDirectionBoth     GraphRequestDirection = "both"
)

func NewGraphRequestDirectionFromString(s string) (GraphRequestDirection, error) {
	switch s {
	case "outgoing":
		return GraphRequestDirectionOutgoing, nil
	case "incoming":
		return GraphRequestDirectionIncoming, nil
	case "both":
		return GraphRequestDirectionBoth, nil
	}
	var t GraphRequestDirection
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GraphRequestDirection) Ptr() *GraphRequestDirection {
	return &g
}
