// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersAddEntityRefRequest(t *testing.T) {
	t.Run("SetEventID", func(t *testing.T) {
		obj := &AddEntityRefRequest{}
		var fernTestValueEventID string
		obj.SetEventID(fernTestValueEventID)
		assert.Equal(t, fernTestValueEventID, obj.EventID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEntityType", func(t *testing.T) {
		obj := &AddEntityRefRequest{}
		var fernTestValueEntityType string
		obj.SetEntityType(fernTestValueEntityType)
		assert.Equal(t, fernTestValueEntityType, obj.EntityType)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEntityID", func(t *testing.T) {
		obj := &AddEntityRefRequest{}
		var fernTestValueEntityID string
		obj.SetEntityID(fernTestValueEntityID)
		assert.Equal(t, fernTestValueEntityID, obj.EntityID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCreatedBy", func(t *testing.T) {
		obj := &AddEntityRefRequest{}
		var fernTestValueCreatedBy *string
		obj.SetCreatedBy(fernTestValueCreatedBy)
		assert.Equal(t, fernTestValueCreatedBy, obj.CreatedBy)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitAddEntityRefRequest(t *testing.T) {
	t.Run("SetEventID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AddEntityRefRequest{}
		var fernTestValueEventID string

		// Act
		obj.SetEventID(fernTestValueEventID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEntityType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AddEntityRefRequest{}
		var fernTestValueEntityType string

		// Act
		obj.SetEntityType(fernTestValueEntityType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEntityID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AddEntityRefRequest{}
		var fernTestValueEntityID string

		// Act
		obj.SetEntityID(fernTestValueEntityID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCreatedBy_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AddEntityRefRequest{}
		var fernTestValueCreatedBy *string

		// Act
		obj.SetCreatedBy(fernTestValueCreatedBy)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCreateLinkRequest(t *testing.T) {
	t.Run("SetSourceEventID", func(t *testing.T) {
		obj := &CreateLinkRequest{}
		var fernTestValueSourceEventID string
		obj.SetSourceEventID(fernTestValueSourceEventID)
		assert.Equal(t, fernTestValueSourceEventID, obj.SourceEventID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTargetEventID", func(t *testing.T) {
		obj := &CreateLinkRequest{}
		var fernTestValueTargetEventID string
		obj.SetTargetEventID(fernTestValueTargetEventID)
		assert.Equal(t, fernTestValueTargetEventID, obj.TargetEventID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLinkType", func(t *testing.T) {
		obj := &CreateLinkRequest{}
		var fernTestValueLinkType string
		obj.SetLinkType(fernTestValueLinkType)
		assert.Equal(t, fernTestValueLinkType, obj.LinkType)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetConfidence", func(t *testing.T) {
		obj := &CreateLinkRequest{}
		var fernTestValueConfidence float64
		obj.SetConfidence(fernTestValueConfidence)
		assert.Equal(t, fernTestValueConfidence, obj.Confidence)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetReasoning", func(t *testing.T) {
		obj := &CreateLinkRequest{}
		var fernTestValueReasoning *string
		obj.SetReasoning(fernTestValueReasoning)
		assert.Equal(t, fernTestValueReasoning, obj.Reasoning)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCreatedBy", func(t *testing.T) {
		obj := &CreateLinkRequest{}
		var fernTestValueCreatedBy *string
		obj.SetCreatedBy(fernTestValueCreatedBy)
		assert.Equal(t, fernTestValueCreatedBy, obj.CreatedBy)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitCreateLinkRequest(t *testing.T) {
	t.Run("SetSourceEventID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateLinkRequest{}
		var fernTestValueSourceEventID string

		// Act
		obj.SetSourceEventID(fernTestValueSourceEventID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTargetEventID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateLinkRequest{}
		var fernTestValueTargetEventID string

		// Act
		obj.SetTargetEventID(fernTestValueTargetEventID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLinkType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateLinkRequest{}
		var fernTestValueLinkType string

		// Act
		obj.SetLinkType(fernTestValueLinkType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetConfidence_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateLinkRequest{}
		var fernTestValueConfidence float64

		// Act
		obj.SetConfidence(fernTestValueConfidence)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetReasoning_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateLinkRequest{}
		var fernTestValueReasoning *string

		// Act
		obj.SetReasoning(fernTestValueReasoning)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCreatedBy_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateLinkRequest{}
		var fernTestValueCreatedBy *string

		// Act
		obj.SetCreatedBy(fernTestValueCreatedBy)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersLinkEntityRequest(t *testing.T) {
	t.Run("SetFromEntityType", func(t *testing.T) {
		obj := &LinkEntityRequest{}
		var fernTestValueFromEntityType string
		obj.SetFromEntityType(fernTestValueFromEntityType)
		assert.Equal(t, fernTestValueFromEntityType, obj.FromEntityType)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetFromEntityID", func(t *testing.T) {
		obj := &LinkEntityRequest{}
		var fernTestValueFromEntityID string
		obj.SetFromEntityID(fernTestValueFromEntityID)
		assert.Equal(t, fernTestValueFromEntityID, obj.FromEntityID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetToEntityType", func(t *testing.T) {
		obj := &LinkEntityRequest{}
		var fernTestValueToEntityType string
		obj.SetToEntityType(fernTestValueToEntityType)
		assert.Equal(t, fernTestValueToEntityType, obj.ToEntityType)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetToEntityID", func(t *testing.T) {
		obj := &LinkEntityRequest{}
		var fernTestValueToEntityID string
		obj.SetToEntityID(fernTestValueToEntityID)
		assert.Equal(t, fernTestValueToEntityID, obj.ToEntityID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCreatedBy", func(t *testing.T) {
		obj := &LinkEntityRequest{}
		var fernTestValueCreatedBy *string
		obj.SetCreatedBy(fernTestValueCreatedBy)
		assert.Equal(t, fernTestValueCreatedBy, obj.CreatedBy)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitLinkEntityRequest(t *testing.T) {
	t.Run("SetFromEntityType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &LinkEntityRequest{}
		var fernTestValueFromEntityType string

		// Act
		obj.SetFromEntityType(fernTestValueFromEntityType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetFromEntityID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &LinkEntityRequest{}
		var fernTestValueFromEntityID string

		// Act
		obj.SetFromEntityID(fernTestValueFromEntityID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetToEntityType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &LinkEntityRequest{}
		var fernTestValueToEntityType string

		// Act
		obj.SetToEntityType(fernTestValueToEntityType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetToEntityID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &LinkEntityRequest{}
		var fernTestValueToEntityID string

		// Act
		obj.SetToEntityID(fernTestValueToEntityID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCreatedBy_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &LinkEntityRequest{}
		var fernTestValueCreatedBy *string

		// Act
		obj.SetCreatedBy(fernTestValueCreatedBy)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGraphRequest(t *testing.T) {
	t.Run("SetStartEventID", func(t *testing.T) {
		obj := &GraphRequest{}
		var fernTestValueStartEventID string
		obj.SetStartEventID(fernTestValueStartEventID)
		assert.Equal(t, fernTestValueStartEventID, obj.StartEventID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDirection", func(t *testing.T) {
		obj := &GraphRequest{}
		var fernTestValueDirection GraphRequestDirection
		obj.SetDirection(fernTestValueDirection)
		assert.Equal(t, fernTestValueDirection, obj.Direction)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLinkTypes", func(t *testing.T) {
		obj := &GraphRequest{}
		var fernTestValueLinkTypes []string
		obj.SetLinkTypes(fernTestValueLinkTypes)
		assert.Equal(t, fernTestValueLinkTypes, obj.LinkTypes)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMaxDepth", func(t *testing.T) {
		obj := &GraphRequest{}
		var fernTestValueMaxDepth *int
		obj.SetMaxDepth(fernTestValueMaxDepth)
		assert.Equal(t, fernTestValueMaxDepth, obj.MaxDepth)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMinConfidence", func(t *testing.T) {
		obj := &GraphRequest{}
		var fernTestValueMinConfidence *float64
		obj.SetMinConfidence(fernTestValueMinConfidence)
		assert.Equal(t, fernTestValueMinConfidence, obj.MinConfidence)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGraphRequest(t *testing.T) {
	t.Run("SetStartEventID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GraphRequest{}
		var fernTestValueStartEventID string

		// Act
		obj.SetStartEventID(fernTestValueStartEventID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDirection_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GraphRequest{}
		var fernTestValueDirection GraphRequestDirection

		// Act
		obj.SetDirection(fernTestValueDirection)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLinkTypes_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GraphRequest{}
		var fernTestValueLinkTypes []string

		// Act
		obj.SetLinkTypes(fernTestValueLinkTypes)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMaxDepth_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GraphRequest{}
		var fernTestValueMaxDepth *int

		// Act
		obj.SetMaxDepth(fernTestValueMaxDepth)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMinConfidence_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GraphRequest{}
		var fernTestValueMinConfidence *float64

		// Act
		obj.SetMinConfidence(fernTestValueMinConfidence)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCreateLinkResponse(t *testing.T) {
	t.Run("SetLinkID", func(t *testing.T) {
		obj := &CreateLinkResponse{}
		var fernTestValueLinkID string
		obj.SetLinkID(fernTestValueLinkID)
		assert.Equal(t, fernTestValueLinkID, obj.LinkID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersCreateLinkResponse(t *testing.T) {
	t.Run("GetLinkID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateLinkResponse{}
		var expected string
		obj.LinkID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLinkID(), "getter should return the property value")
	})

	t.Run("GetLinkID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateLinkResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLinkID() // Should return zero value
	})

}

func TestSettersMarkExplicitCreateLinkResponse(t *testing.T) {
	t.Run("SetLinkID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateLinkResponse{}
		var fernTestValueLinkID string

		// Act
		obj.SetLinkID(fernTestValueLinkID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersLinkEntityResponse(t *testing.T) {
	t.Run("SetLinkedCount", func(t *testing.T) {
		obj := &LinkEntityResponse{}
		var fernTestValueLinkedCount int
		obj.SetLinkedCount(fernTestValueLinkedCount)
		assert.Equal(t, fernTestValueLinkedCount, obj.LinkedCount)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersLinkEntityResponse(t *testing.T) {
	t.Run("GetLinkedCount", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &LinkEntityResponse{}
		var expected int
		obj.LinkedCount = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLinkedCount(), "getter should return the property value")
	})

	t.Run("GetLinkedCount_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *LinkEntityResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLinkedCount() // Should return zero value
	})

}

func TestSettersMarkExplicitLinkEntityResponse(t *testing.T) {
	t.Run("SetLinkedCount_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &LinkEntityResponse{}
		var fernTestValueLinkedCount int

		// Act
		obj.SetLinkedCount(fernTestValueLinkedCount)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersStatusResponse(t *testing.T) {
	t.Run("SetStatus", func(t *testing.T) {
		obj := &StatusResponse{}
		var fernTestValueStatus string
		obj.SetStatus(fernTestValueStatus)
		assert.Equal(t, fernTestValueStatus, obj.Status)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersStatusResponse(t *testing.T) {
	t.Run("GetStatus", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &StatusResponse{}
		var expected string
		obj.Status = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStatus(), "getter should return the property value")
	})

	t.Run("GetStatus_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *StatusResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStatus() // Should return zero value
	})

}

func TestSettersMarkExplicitStatusResponse(t *testing.T) {
	t.Run("SetStatus_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &StatusResponse{}
		var fernTestValueStatus string

		// Act
		obj.SetStatus(fernTestValueStatus)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingCreateLinkResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateLinkResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled CreateLinkResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj CreateLinkResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj CreateLinkResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingLinkEntityResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &LinkEntityResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled LinkEntityResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj LinkEntityResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj LinkEntityResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingStatusResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &StatusResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled StatusResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj StatusResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj StatusResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringCreateLinkResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &CreateLinkResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateLinkResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringLinkEntityResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &LinkEntityResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *LinkEntityResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringStatusResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &StatusResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *StatusResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumGraphRequestDirection(t *testing.T) {
	t.Run("NewFromString_outgoing", func(t *testing.T) {
		t.Parallel()
		val, err := NewGraphRequestDirectionFromString("outgoing")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, GraphRequestDirection("outgoing"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_incoming", func(t *testing.T) {
		t.Parallel()
		val, err := NewGraphRequestDirectionFromString("incoming")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, GraphRequestDirection("incoming"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_both", func(t *testing.T) {
		t.Parallel()
		val, err := NewGraphRequestDirectionFromString("both")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, GraphRequestDirection("both"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewGraphRequestDirectionFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewGraphRequestDirectionFromString("outgoing")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesCreateLinkResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &CreateLinkResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateLinkResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesLinkEntityResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &LinkEntityResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *LinkEntityResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesStatusResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &StatusResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *StatusResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
