// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	internal "github.com/chronicle-labs-ai/chronicle-go/internal"
	big "math/big"
)

var (
	searchRequestFieldQuery      = big.NewInt(1 << 0)
	searchRequestFieldSource     = big.NewInt(1 << 1)
	searchRequestFieldEntityType = big.NewInt(1 << 2)
	searchRequestFieldEntityID   = big.NewInt(1 << 3)
	searchRequestFieldLimit      = big.NewInt(1 << 4)
	searchRequestFieldCursor     = big.NewInt(1 << 5)
)

type SearchRequest struct {
	Query      string  `json:"query" url:"-"`
	Source     *string `json:"source,omitempty" url:"-"`
	EntityType *string `json:"entity_type,omitempty" url:"-"`
	EntityID   *string `json:"entity_id,omitempty" url:"-"`
	Limit      *int    `json:"limit,omitempty" url:"-"`
	// Opaque position returned by the preceding search page.
	Cursor *string `json:"cursor,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SearchRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetQuery sets the Query field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchRequest) SetQuery(query string) {
	s.Query = query
	s.require(searchRequestFieldQuery)
}

// SetSource sets the Source field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchRequest) SetSource(source *string) {
	s.Source = source
	s.require(searchRequestFieldSource)
}

// SetEntityType sets the EntityType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchRequest) SetEntityType(entityType *string) {
	s.EntityType = entityType
	s.require(searchRequestFieldEntityType)
}

// SetEntityID sets the EntityID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchRequest) SetEntityID(entityID *string) {
	s.EntityID = entityID
	s.require(searchRequestFieldEntityID)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchRequest) SetLimit(limit *int) {
	s.Limit = limit
	s.require(searchRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchRequest) SetCursor(cursor *string) {
	s.Cursor = cursor
	s.require(searchRequestFieldCursor)
}

func (s *SearchRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler SearchRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*s = SearchRequest(body)
	return nil
}

func (s *SearchRequest) MarshalJSON() ([]byte, error) {
	type embed SearchRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}
