// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/chronicle-labs-ai/chronicle-go/internal"
	big "math/big"
	time "time"
)

// A stored entity reference, attributed and timestamped.
var (
	entityRefFieldEventID    = big.NewInt(1 << 0)
	entityRefFieldEntityType = big.NewInt(1 << 1)
	entityRefFieldEntityID   = big.NewInt(1 << 2)
	entityRefFieldCreatedBy  = big.NewInt(1 << 3)
	entityRefFieldCreatedAt  = big.NewInt(1 << 4)
)

type EntityRef struct {
	EventID    string `json:"event_id" url:"event_id"`
	EntityType string `json:"entity_type" url:"entity_type"`
	EntityID   string `json:"entity_id" url:"entity_id"`
	// What created the reference, for example ingestion or a linker agent.
	CreatedBy string    `json:"created_by" url:"created_by"`
	CreatedAt time.Time `json:"created_at" url:"created_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EntityRef) GetEventID() string {
	if e == nil {
		return ""
	}
	return e.EventID
}

func (e *EntityRef) GetEntityType() string {
	if e == nil {
		return ""
	}
	return e.EntityType
}

func (e *EntityRef) GetEntityID() string {
	if e == nil {
		return ""
	}
	return e.EntityID
}

func (e *EntityRef) GetCreatedBy() string {
	if e == nil {
		return ""
	}
	return e.CreatedBy
}

func (e *EntityRef) GetCreatedAt() time.Time {
	if e == nil {
		return time.Time{}
	}
	return e.CreatedAt
}

func (e *EntityRef) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *EntityRef) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetEventID sets the EventID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityRef) SetEventID(eventID string) {
	e.EventID = eventID
	e.require(entityRefFieldEventID)
}

// SetEntityType sets the EntityType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityRef) SetEntityType(entityType string) {
	e.EntityType = entityType
	e.require(entityRefFieldEntityType)
}

// SetEntityID sets the EntityID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityRef) SetEntityID(entityID string) {
	e.EntityID = entityID
	e.require(entityRefFieldEntityID)
}

// SetCreatedBy sets the CreatedBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityRef) SetCreatedBy(createdBy string) {
	e.CreatedBy = createdBy
	e.require(entityRefFieldCreatedBy)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EntityRef) SetCreatedAt(createdAt time.Time) {
	e.CreatedAt = createdAt
	e.require(entityRefFieldCreatedAt)
}

func (e *EntityRef) UnmarshalJSON(data []byte) error {
	type embed EntityRef
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
	}{
		embed: embed(*e),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*e = EntityRef(unmarshaler.embed)
	e.CreatedAt = unmarshaler.CreatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EntityRef) MarshalJSON() ([]byte, error) {
	type embed EntityRef
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
	}{
		embed:     embed(*e),
		CreatedAt: internal.NewDateTime(e.CreatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EntityRef) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

// RFC 9457 problem details, served as `application/problem+json`. The `code` member is the stable machine-readable slug to branch on; `type` and `title` are stable per problem class, and `detail` varies per occurrence. The `error` and `message` members are retained for existing clients and carry the same values as `code` and `detail`. The request identifier appears both in the `x-request-id` response header, for code to read and log, and in the `request_id` member, so it survives being copied into a support thread.
var (
	errorResponseFieldType      = big.NewInt(1 << 0)
	errorResponseFieldTitle     = big.NewInt(1 << 1)
	errorResponseFieldStatus    = big.NewInt(1 << 2)
	errorResponseFieldDetail    = big.NewInt(1 << 3)
	errorResponseFieldCode      = big.NewInt(1 << 4)
	errorResponseFieldError     = big.NewInt(1 << 5)
	errorResponseFieldMessage   = big.NewInt(1 << 6)
	errorResponseFieldRetryable = big.NewInt(1 << 7)
	errorResponseFieldRequestID = big.NewInt(1 << 8)
	errorResponseFieldDetails   = big.NewInt(1 << 9)
)

type ErrorResponse struct {
	// URI identifying the problem class
	Type string `json:"type" url:"type"`
	// Short summary of the problem class, stable across occurrences
	Title string `json:"title" url:"title"`
	// HTTP status code, always equal to the response status
	Status int `json:"status" url:"status"`
	// Explanation specific to this occurrence
	Detail string `json:"detail" url:"detail"`
	// Stable machine-readable slug to branch on
	Code ErrorResponseCode `json:"code" url:"code"`
	// Retained for existing clients. Same value as `code`.
	Error string `json:"error" url:"error"`
	// Retained for existing clients. Same value as `detail`.
	Message string `json:"message" url:"message"`
	// Whether the same request may succeed when retried without modification
	Retryable bool `json:"retryable" url:"retryable"`
	// Same value as the `x-request-id` response header. Quote it when reporting a problem; it identifies the exact request in our logs.
	RequestID *string `json:"request_id,omitempty" url:"request_id,omitempty"`
	Details   any     `json:"details,omitempty" url:"details,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *ErrorResponse) GetType() string {
	if e == nil {
		return ""
	}
	return e.Type
}

func (e *ErrorResponse) GetTitle() string {
	if e == nil {
		return ""
	}
	return e.Title
}

func (e *ErrorResponse) GetStatus() int {
	if e == nil {
		return 0
	}
	return e.Status
}

func (e *ErrorResponse) GetDetail() string {
	if e == nil {
		return ""
	}
	return e.Detail
}

func (e *ErrorResponse) GetCode() ErrorResponseCode {
	if e == nil {
		return ""
	}
	return e.Code
}

func (e *ErrorResponse) GetError() string {
	if e == nil {
		return ""
	}
	return e.Error
}

func (e *ErrorResponse) GetMessage() string {
	if e == nil {
		return ""
	}
	return e.Message
}

func (e *ErrorResponse) GetRetryable() bool {
	if e == nil {
		return false
	}
	return e.Retryable
}

func (e *ErrorResponse) GetRequestID() *string {
	if e == nil {
		return nil
	}
	return e.RequestID
}

func (e *ErrorResponse) GetDetails() any {
	if e == nil {
		return nil
	}
	return e.Details
}

func (e *ErrorResponse) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *ErrorResponse) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ErrorResponse) SetType(type_ string) {
	e.Type = type_
	e.require(errorResponseFieldType)
}

// SetTitle sets the Title field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ErrorResponse) SetTitle(title string) {
	e.Title = title
	e.require(errorResponseFieldTitle)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ErrorResponse) SetStatus(status int) {
	e.Status = status
	e.require(errorResponseFieldStatus)
}

// SetDetail sets the Detail field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ErrorResponse) SetDetail(detail string) {
	e.Detail = detail
	e.require(errorResponseFieldDetail)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ErrorResponse) SetCode(code ErrorResponseCode) {
	e.Code = code
	e.require(errorResponseFieldCode)
}

// SetError sets the Error field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ErrorResponse) SetError(error_ string) {
	e.Error = error_
	e.require(errorResponseFieldError)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ErrorResponse) SetMessage(message string) {
	e.Message = message
	e.require(errorResponseFieldMessage)
}

// SetRetryable sets the Retryable field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ErrorResponse) SetRetryable(retryable bool) {
	e.Retryable = retryable
	e.require(errorResponseFieldRetryable)
}

// SetRequestID sets the RequestID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ErrorResponse) SetRequestID(requestID *string) {
	e.RequestID = requestID
	e.require(errorResponseFieldRequestID)
}

// SetDetails sets the Details field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ErrorResponse) SetDetails(details any) {
	e.Details = details
	e.require(errorResponseFieldDetails)
}

func (e *ErrorResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ErrorResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = ErrorResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *ErrorResponse) MarshalJSON() ([]byte, error) {
	type embed ErrorResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *ErrorResponse) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

// Stable machine-readable slug to branch on
type ErrorResponseCode string

const (
	ErrorResponseCodeNotFound                  ErrorResponseCode = "not_found"
	ErrorResponseCodeBadRequest                ErrorResponseCode = "bad_request"
	ErrorResponseCodeUnauthorized              ErrorResponseCode = "unauthorized"
	ErrorResponseCodeValidationError           ErrorResponseCode = "validation_error"
	ErrorResponseCodeUnsupportedMediaType      ErrorResponseCode = "unsupported_media_type"
	ErrorResponseCodePayloadTooLarge           ErrorResponseCode = "payload_too_large"
	ErrorResponseCodeRateLimited               ErrorResponseCode = "rate_limited"
	ErrorResponseCodeStreamReplayLimitExceeded ErrorResponseCode = "stream_replay_limit_exceeded"
	ErrorResponseCodeStreamUnavailable         ErrorResponseCode = "stream_unavailable"
	ErrorResponseCodeServiceOverloaded         ErrorResponseCode = "service_overloaded"
	ErrorResponseCodeRequestTimeout            ErrorResponseCode = "request_timeout"
	ErrorResponseCodeStreamError               ErrorResponseCode = "stream_error"
	ErrorResponseCodeStoreError                ErrorResponseCode = "store_error"
	ErrorResponseCodeInternalError             ErrorResponseCode = "internal_error"
)

func NewErrorResponseCodeFromString(s string) (ErrorResponseCode, error) {
	switch s {
	case "not_found":
		return ErrorResponseCodeNotFound, nil
	case "bad_request":
		return ErrorResponseCodeBadRequest, nil
	case "unauthorized":
		return ErrorResponseCodeUnauthorized, nil
	case "validation_error":
		return ErrorResponseCodeValidationError, nil
	case "unsupported_media_type":
		return ErrorResponseCodeUnsupportedMediaType, nil
	case "payload_too_large":
		return ErrorResponseCodePayloadTooLarge, nil
	case "rate_limited":
		return ErrorResponseCodeRateLimited, nil
	case "stream_replay_limit_exceeded":
		return ErrorResponseCodeStreamReplayLimitExceeded, nil
	case "stream_unavailable":
		return ErrorResponseCodeStreamUnavailable, nil
	case "service_overloaded":
		return ErrorResponseCodeServiceOverloaded, nil
	case "request_timeout":
		return ErrorResponseCodeRequestTimeout, nil
	case "stream_error":
		return ErrorResponseCodeStreamError, nil
	case "store_error":
		return ErrorResponseCodeStoreError, nil
	case "internal_error":
		return ErrorResponseCodeInternalError, nil
	}
	var t ErrorResponseCode
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (e ErrorResponseCode) Ptr() *ErrorResponseCode {
	return &e
}

// A stored event. Immutable once written.
var (
	eventFieldEventID       = big.NewInt(1 << 0)
	eventFieldOrgID         = big.NewInt(1 << 1)
	eventFieldSource        = big.NewInt(1 << 2)
	eventFieldTopic         = big.NewInt(1 << 3)
	eventFieldEventType     = big.NewInt(1 << 4)
	eventFieldEventTime     = big.NewInt(1 << 5)
	eventFieldIngestionTime = big.NewInt(1 << 6)
	eventFieldPayload       = big.NewInt(1 << 7)
	eventFieldMedia         = big.NewInt(1 << 8)
	eventFieldEntityRefs    = big.NewInt(1 << 9)
	eventFieldRawBody       = big.NewInt(1 << 10)
)

type Event struct {
	// Time-ordered identifier, sorts in creation order.
	EventID string `json:"event_id" url:"event_id"`
	// Organisation the event belongs to.
	OrgID     string `json:"org_id" url:"org_id"`
	Source    string `json:"source" url:"source"`
	Topic     string `json:"topic" url:"topic"`
	EventType string `json:"event_type" url:"event_type"`
	// When the event happened at the source.
	EventTime time.Time `json:"event_time" url:"event_time"`
	// When Chronicle received it.
	IngestionTime time.Time `json:"ingestion_time" url:"ingestion_time"`
	// Source-defined body. Free-form by design.
	Payload map[string]any   `json:"payload,omitempty" url:"payload,omitempty"`
	Media   *MediaAttachment `json:"media,omitempty" url:"media,omitempty"`
	// Entity references supplied with the event at ingest time.
	EntityRefs []*PendingEntityRef `json:"entity_refs,omitempty" url:"entity_refs,omitempty"`
	RawBody    *string             `json:"raw_body,omitempty" url:"raw_body,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *Event) GetEventID() string {
	if e == nil {
		return ""
	}
	return e.EventID
}

func (e *Event) GetOrgID() string {
	if e == nil {
		return ""
	}
	return e.OrgID
}

func (e *Event) GetSource() string {
	if e == nil {
		return ""
	}
	return e.Source
}

func (e *Event) GetTopic() string {
	if e == nil {
		return ""
	}
	return e.Topic
}

func (e *Event) GetEventType() string {
	if e == nil {
		return ""
	}
	return e.EventType
}

func (e *Event) GetEventTime() time.Time {
	if e == nil {
		return time.Time{}
	}
	return e.EventTime
}

func (e *Event) GetIngestionTime() time.Time {
	if e == nil {
		return time.Time{}
	}
	return e.IngestionTime
}

func (e *Event) GetPayload() map[string]any {
	if e == nil {
		return nil
	}
	return e.Payload
}

func (e *Event) GetMedia() *MediaAttachment {
	if e == nil {
		return nil
	}
	return e.Media
}

func (e *Event) GetEntityRefs() []*PendingEntityRef {
	if e == nil {
		return nil
	}
	return e.EntityRefs
}

func (e *Event) GetRawBody() *string {
	if e == nil {
		return nil
	}
	return e.RawBody
}

func (e *Event) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *Event) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetEventID sets the EventID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *Event) SetEventID(eventID string) {
	e.EventID = eventID
	e.require(eventFieldEventID)
}

// SetOrgID sets the OrgID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *Event) SetOrgID(orgID string) {
	e.OrgID = orgID
	e.require(eventFieldOrgID)
}

// SetSource sets the Source field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *Event) SetSource(source string) {
	e.Source = source
	e.require(eventFieldSource)
}

// SetTopic sets the Topic field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *Event) SetTopic(topic string) {
	e.Topic = topic
	e.require(eventFieldTopic)
}

// SetEventType sets the EventType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *Event) SetEventType(eventType string) {
	e.EventType = eventType
	e.require(eventFieldEventType)
}

// SetEventTime sets the EventTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *Event) SetEventTime(eventTime time.Time) {
	e.EventTime = eventTime
	e.require(eventFieldEventTime)
}

// SetIngestionTime sets the IngestionTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *Event) SetIngestionTime(ingestionTime time.Time) {
	e.IngestionTime = ingestionTime
	e.require(eventFieldIngestionTime)
}

// SetPayload sets the Payload field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *Event) SetPayload(payload map[string]any) {
	e.Payload = payload
	e.require(eventFieldPayload)
}

// SetMedia sets the Media field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *Event) SetMedia(media *MediaAttachment) {
	e.Media = media
	e.require(eventFieldMedia)
}

// SetEntityRefs sets the EntityRefs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *Event) SetEntityRefs(entityRefs []*PendingEntityRef) {
	e.EntityRefs = entityRefs
	e.require(eventFieldEntityRefs)
}

// SetRawBody sets the RawBody field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *Event) SetRawBody(rawBody *string) {
	e.RawBody = rawBody
	e.require(eventFieldRawBody)
}

func (e *Event) UnmarshalJSON(data []byte) error {
	type embed Event
	var unmarshaler = struct {
		embed
		EventTime     *internal.DateTime `json:"event_time"`
		IngestionTime *internal.DateTime `json:"ingestion_time"`
	}{
		embed: embed(*e),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*e = Event(unmarshaler.embed)
	e.EventTime = unmarshaler.EventTime.Time()
	e.IngestionTime = unmarshaler.IngestionTime.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *Event) MarshalJSON() ([]byte, error) {
	type embed Event
	var marshaler = struct {
		embed
		EventTime     *internal.DateTime `json:"event_time"`
		IngestionTime *internal.DateTime `json:"ingestion_time"`
	}{
		embed:         embed(*e),
		EventTime:     internal.NewDateTime(e.EventTime),
		IngestionTime: internal.NewDateTime(e.IngestionTime),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *Event) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

// A bounded page of events. An absent `next_cursor` means the page is final.
var (
	eventListResponseFieldData       = big.NewInt(1 << 0)
	eventListResponseFieldNextCursor = big.NewInt(1 << 1)
)

type EventListResponse struct {
	Data []*EventResult `json:"data" url:"data"`
	// Opaque position for the next request.
	NextCursor *string `json:"next_cursor,omitempty" url:"next_cursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EventListResponse) GetData() []*EventResult {
	if e == nil {
		return nil
	}
	return e.Data
}

func (e *EventListResponse) GetNextCursor() *string {
	if e == nil {
		return nil
	}
	return e.NextCursor
}

func (e *EventListResponse) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *EventListResponse) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventListResponse) SetData(data []*EventResult) {
	e.Data = data
	e.require(eventListResponseFieldData)
}

// SetNextCursor sets the NextCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventListResponse) SetNextCursor(nextCursor *string) {
	e.NextCursor = nextCursor
	e.require(eventListResponseFieldNextCursor)
}

func (e *EventListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler EventListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EventListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EventListResponse) MarshalJSON() ([]byte, error) {
	type embed EventListResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EventListResponse) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

// An event with its entity references and optional search distance.
var (
	eventResultFieldEvent          = big.NewInt(1 << 0)
	eventResultFieldEntityRefs     = big.NewInt(1 << 1)
	eventResultFieldSearchDistance = big.NewInt(1 << 2)
)

type EventResult struct {
	Event          *Event       `json:"event" url:"event"`
	EntityRefs     []*EntityRef `json:"entity_refs,omitempty" url:"entity_refs,omitempty"`
	SearchDistance *float64     `json:"search_distance,omitempty" url:"search_distance,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EventResult) GetEvent() *Event {
	if e == nil {
		return nil
	}
	return e.Event
}

func (e *EventResult) GetEntityRefs() []*EntityRef {
	if e == nil {
		return nil
	}
	return e.EntityRefs
}

func (e *EventResult) GetSearchDistance() *float64 {
	if e == nil {
		return nil
	}
	return e.SearchDistance
}

func (e *EventResult) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *EventResult) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetEvent sets the Event field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventResult) SetEvent(event *Event) {
	e.Event = event
	e.require(eventResultFieldEvent)
}

// SetEntityRefs sets the EntityRefs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventResult) SetEntityRefs(entityRefs []*EntityRef) {
	e.EntityRefs = entityRefs
	e.require(eventResultFieldEntityRefs)
}

// SetSearchDistance sets the SearchDistance field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventResult) SetSearchDistance(searchDistance *float64) {
	e.SearchDistance = searchDistance
	e.require(eventResultFieldSearchDistance)
}

func (e *EventResult) UnmarshalJSON(data []byte) error {
	type unmarshaler EventResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EventResult(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EventResult) MarshalJSON() ([]byte, error) {
	type embed EventResult
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EventResult) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

// Media attached to an event, stored inline or by reference.
var (
	mediaAttachmentFieldMediaType   = big.NewInt(1 << 0)
	mediaAttachmentFieldInlineBlob  = big.NewInt(1 << 1)
	mediaAttachmentFieldExternalRef = big.NewInt(1 << 2)
	mediaAttachmentFieldSizeBytes   = big.NewInt(1 << 3)
)

type MediaAttachment struct {
	MediaType string `json:"media_type" url:"media_type"`
	// Inline bytes for small media. Absent when stored externally.
	InlineBlob *string `json:"inline_blob,omitempty" url:"inline_blob,omitempty"`
	// URI for externally stored media. Absent when inline.
	ExternalRef *string `json:"external_ref,omitempty" url:"external_ref,omitempty"`
	SizeBytes   int64   `json:"size_bytes" url:"size_bytes"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MediaAttachment) GetMediaType() string {
	if m == nil {
		return ""
	}
	return m.MediaType
}

func (m *MediaAttachment) GetInlineBlob() *string {
	if m == nil {
		return nil
	}
	return m.InlineBlob
}

func (m *MediaAttachment) GetExternalRef() *string {
	if m == nil {
		return nil
	}
	return m.ExternalRef
}

func (m *MediaAttachment) GetSizeBytes() int64 {
	if m == nil {
		return 0
	}
	return m.SizeBytes
}

func (m *MediaAttachment) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MediaAttachment) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetMediaType sets the MediaType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MediaAttachment) SetMediaType(mediaType string) {
	m.MediaType = mediaType
	m.require(mediaAttachmentFieldMediaType)
}

// SetInlineBlob sets the InlineBlob field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MediaAttachment) SetInlineBlob(inlineBlob *string) {
	m.InlineBlob = inlineBlob
	m.require(mediaAttachmentFieldInlineBlob)
}

// SetExternalRef sets the ExternalRef field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MediaAttachment) SetExternalRef(externalRef *string) {
	m.ExternalRef = externalRef
	m.require(mediaAttachmentFieldExternalRef)
}

// SetSizeBytes sets the SizeBytes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MediaAttachment) SetSizeBytes(sizeBytes int64) {
	m.SizeBytes = sizeBytes
	m.require(mediaAttachmentFieldSizeBytes)
}

func (m *MediaAttachment) UnmarshalJSON(data []byte) error {
	type unmarshaler MediaAttachment
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MediaAttachment(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MediaAttachment) MarshalJSON() ([]byte, error) {
	type embed MediaAttachment
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MediaAttachment) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

// An entity reference as supplied at ingest, before it is stored.
var (
	pendingEntityRefFieldEntityType = big.NewInt(1 << 0)
	pendingEntityRefFieldEntityID   = big.NewInt(1 << 1)
)

type PendingEntityRef struct {
	EntityType string `json:"entity_type" url:"entity_type"`
	EntityID   string `json:"entity_id" url:"entity_id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PendingEntityRef) GetEntityType() string {
	if p == nil {
		return ""
	}
	return p.EntityType
}

func (p *PendingEntityRef) GetEntityID() string {
	if p == nil {
		return ""
	}
	return p.EntityID
}

func (p *PendingEntityRef) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PendingEntityRef) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetEntityType sets the EntityType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PendingEntityRef) SetEntityType(entityType string) {
	p.EntityType = entityType
	p.require(pendingEntityRefFieldEntityType)
}

// SetEntityID sets the EntityID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PendingEntityRef) SetEntityID(entityID string) {
	p.EntityID = entityID
	p.require(pendingEntityRefFieldEntityID)
}

func (p *PendingEntityRef) UnmarshalJSON(data []byte) error {
	type unmarshaler PendingEntityRef
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PendingEntityRef(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PendingEntityRef) MarshalJSON() ([]byte, error) {
	type embed PendingEntityRef
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PendingEntityRef) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}
