// Code generated by Fern. DO NOT EDIT.

// Long-running backtest jobs, trials, evidence, and progress streams. Creation returns 202 with a job identifier. Poll the job resource or follow its SSE stream for progress and terminal status; fetch trials for result and error evidence. Jobs may be cancelled through the cancel operation. After an ambiguous launch failure, retry with the same Idempotency-Key and identical payload rather than creating a second job.
package backtests
