// Code generated by Fern. DO NOT EDIT.

package backtests

import (
	context "context"
	http "net/http"

	chroniclego "github.com/chronicle-labs-ai/chronicle-go"
	core "github.com/chronicle-labs-ai/chronicle-go/core"
	internal "github.com/chronicle-labs-ai/chronicle-go/internal"
	option "github.com/chronicle-labs-ai/chronicle-go/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) GetBacktestsAvailability(
	ctx context.Context,
	opts ...option.RequestOption,
) (*core.Response[*chroniclego.BacktestsAvailability], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.chroniclelabs.ai",
	)
	endpointURL := baseURL + "/v1/backtests/availability"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *chroniclego.BacktestsAvailability
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(chroniclego.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*chroniclego.BacktestsAvailability]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ListBacktestJobs(
	ctx context.Context,
	request *chroniclego.ListBacktestJobsRequest,
	opts ...option.RequestOption,
) (*core.Response[*chroniclego.ListBacktestJobsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.chroniclelabs.ai",
	)
	endpointURL := baseURL + "/v1/backtests/jobs"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *chroniclego.ListBacktestJobsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(chroniclego.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*chroniclego.ListBacktestJobsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateBacktestJob(
	ctx context.Context,
	request *chroniclego.CreateBacktestJobRequest,
	opts ...option.RequestOption,
) (*core.Response[*chroniclego.CreateBacktestJobResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.chroniclelabs.ai",
	)
	endpointURL := baseURL + "/v1/backtests/jobs"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	if request.IdempotencyKey != nil {
		headers.Add("Idempotency-Key", *request.IdempotencyKey)
	}
	headers.Add("Content-Type", "application/json")
	var response *chroniclego.CreateBacktestJobResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(chroniclego.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*chroniclego.CreateBacktestJobResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetBacktestJob(
	ctx context.Context,
	request *chroniclego.GetBacktestJobRequest,
	opts ...option.RequestOption,
) (*core.Response[*chroniclego.BacktestJobDetailResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.chroniclelabs.ai",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/backtests/jobs/%v",
		request.JobID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *chroniclego.BacktestJobDetailResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(chroniclego.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*chroniclego.BacktestJobDetailResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ListBacktestJobTrials(
	ctx context.Context,
	request *chroniclego.ListBacktestJobTrialsRequest,
	opts ...option.RequestOption,
) (*core.Response[*chroniclego.ListBacktestJobTrialsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.chroniclelabs.ai",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/backtests/jobs/%v/trials",
		request.JobID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *chroniclego.ListBacktestJobTrialsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(chroniclego.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*chroniclego.ListBacktestJobTrialsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetBacktestTrial(
	ctx context.Context,
	request *chroniclego.GetBacktestTrialRequest,
	opts ...option.RequestOption,
) (*core.Response[*chroniclego.BacktestTrialDetailResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.chroniclelabs.ai",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/backtests/jobs/%v/trials/%v",
		request.JobID,
		request.TrialID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *chroniclego.BacktestTrialDetailResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(chroniclego.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*chroniclego.BacktestTrialDetailResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CancelBacktestJob(
	ctx context.Context,
	request *chroniclego.CancelBacktestJobRequest,
	opts ...option.RequestOption,
) (*core.Response[*chroniclego.CancelBacktestJobResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.chroniclelabs.ai",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/backtests/jobs/%v/cancel",
		request.JobID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *chroniclego.CancelBacktestJobResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(chroniclego.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*chroniclego.CancelBacktestJobResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
