// Code generated by Fern. DO NOT EDIT.

package search

import (
	context "context"

	chroniclego "github.com/chronicle-labs-ai/chronicle-go"
	core "github.com/chronicle-labs-ai/chronicle-go/core"
	internal "github.com/chronicle-labs-ai/chronicle-go/internal"
	option "github.com/chronicle-labs-ai/chronicle-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Requires scope events:read or events:write. The page size is capped at 200 and a cursor can advance through at most 1,000 relevance-ranked results. Each request consumes 5 rate-limit units.
//
// Example:
//
//	request := &chroniclego.SearchRequest{
//	    Query: "query",
//	}
//	client.Search.Events(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Events(
	ctx context.Context,
	request *chroniclego.SearchRequest,
	opts ...option.RequestOption,
) (*chroniclego.EventListResponse, error) {
	response, err := c.WithRawResponse.Events(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
