// Code generated by Fern. DO NOT EDIT.

package discover

import (
	context "context"

	chroniclego "github.com/chronicle-labs-ai/chronicle-go"
	core "github.com/chronicle-labs-ai/chronicle-go/core"
	internal "github.com/chronicle-labs-ai/chronicle-go/internal"
	option "github.com/chronicle-labs-ai/chronicle-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Requires scope events:read or events:write. Returns the complete source metadata set without pagination.
//
// Example:
//
//	client.Discover.ListSources(
//	    context.TODO(),
//	)
func (c *Client) ListSources(
	ctx context.Context,
	opts ...option.RequestOption,
) (*chroniclego.SourceListResponse, error) {
	response, err := c.WithRawResponse.ListSources(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Requires scope events:read or events:write. Returns the complete entity-type metadata set without pagination.
//
// Example:
//
//	client.Discover.ListEntityTypes(
//	    context.TODO(),
//	)
func (c *Client) ListEntityTypes(
	ctx context.Context,
	opts ...option.RequestOption,
) (*chroniclego.EntityTypeListResponse, error) {
	response, err := c.WithRawResponse.ListEntityTypes(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Requires scope events:read or events:write. Entities are ordered by event count and entity ID. The limit is capped at 200; pass `next_cursor` as `cursor`.
//
// Example:
//
//	request := &chroniclego.ListEntitiesRequest{
//	    EntityType: "entity_type",
//	}
//	client.Discover.ListEntities(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListEntities(
	ctx context.Context,
	request *chroniclego.ListEntitiesRequest,
	opts ...option.RequestOption,
) (*chroniclego.EntityListResponse, error) {
	response, err := c.WithRawResponse.ListEntities(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Requires scope events:read or events:write.
//
// Example:
//
//	request := &chroniclego.GetEventSchemaRequest{
//	    Source: "source",
//	    EventType: "event_type",
//	}
//	client.Discover.GetEventSchema(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetEventSchema(
	ctx context.Context,
	request *chroniclego.GetEventSchemaRequest,
	opts ...option.RequestOption,
) (*chroniclego.SourceSchema, error) {
	response, err := c.WithRawResponse.GetEventSchema(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
