// Code generated by Fern. DO NOT EDIT.

package environments

import (
	context "context"

	chroniclego "github.com/chronicle-labs-ai/chronicle-go"
	core "github.com/chronicle-labs-ai/chronicle-go/core"
	internal "github.com/chronicle-labs-ai/chronicle-go/internal"
	option "github.com/chronicle-labs-ai/chronicle-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Example:
//
//	client.Environments.ListEnvironments(
//	    context.TODO(),
//	)
func (c *Client) ListEnvironments(
	ctx context.Context,
	opts ...option.RequestOption,
) (*chroniclego.ListEnvironmentsResponse, error) {
	response, err := c.WithRawResponse.ListEnvironments(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &chroniclego.CreateEnvironmentRequest{
//	    Slug: "support-sandbox",
//	    Label: "Support sandbox",
//	    Description: chroniclego.String(
//	        "Isolated environment for support-agent backtests.",
//	    ),
//	}
//	client.Environments.CreateEnvironment(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CreateEnvironment(
	ctx context.Context,
	request *chroniclego.CreateEnvironmentRequest,
	opts ...option.RequestOption,
) (*chroniclego.EnvironmentResponse, error) {
	response, err := c.WithRawResponse.CreateEnvironment(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &chroniclego.GetEnvironmentRequest{
//	    EnvironmentID: "environment_id",
//	}
//	client.Environments.GetEnvironment(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetEnvironment(
	ctx context.Context,
	request *chroniclego.GetEnvironmentRequest,
	opts ...option.RequestOption,
) (*chroniclego.EnvironmentResponse, error) {
	response, err := c.WithRawResponse.GetEnvironment(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &chroniclego.ListEnvironmentVersionsRequest{
//	    EnvironmentID: "environment_id",
//	}
//	client.Environments.ListEnvironmentVersions(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListEnvironmentVersions(
	ctx context.Context,
	request *chroniclego.ListEnvironmentVersionsRequest,
	opts ...option.RequestOption,
) ([]*chroniclego.EnvironmentVersionRecord, error) {
	response, err := c.WithRawResponse.ListEnvironmentVersions(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &chroniclego.CreateEnvironmentVersionRequest{
//	    EnvironmentID: "environment_id",
//	    Version: "version",
//	}
//	client.Environments.CreateEnvironmentVersion(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CreateEnvironmentVersion(
	ctx context.Context,
	request *chroniclego.CreateEnvironmentVersionRequest,
	opts ...option.RequestOption,
) (*chroniclego.EnvironmentVersionResponse, error) {
	response, err := c.WithRawResponse.CreateEnvironmentVersion(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &chroniclego.GetEnvironmentVersionRequest{
//	    EnvironmentID: "environment_id",
//	    VersionSelector: "version_selector",
//	}
//	client.Environments.GetEnvironmentVersion(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetEnvironmentVersion(
	ctx context.Context,
	request *chroniclego.GetEnvironmentVersionRequest,
	opts ...option.RequestOption,
) (*chroniclego.EnvironmentVersionResponse, error) {
	response, err := c.WithRawResponse.GetEnvironmentVersion(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &chroniclego.CompileEnvironmentRequest{
//	    EnvironmentID: "environment_id",
//	    VersionSelector: "version_selector",
//	    DatasetSnapshotID: "datasetSnapshotId",
//	    ScenarioID: "scenarioId",
//	}
//	client.Environments.CompileEnvironmentVersion(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CompileEnvironmentVersion(
	ctx context.Context,
	request *chroniclego.CompileEnvironmentRequest,
	opts ...option.RequestOption,
) (*chroniclego.CompileEnvironmentResponse, error) {
	response, err := c.WithRawResponse.CompileEnvironmentVersion(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
