// Code generated by Fern. DO NOT EDIT.

package environments

import (
	context "context"
	http "net/http"

	chroniclego "github.com/chronicle-labs-ai/chronicle-go"
	core "github.com/chronicle-labs-ai/chronicle-go/core"
	internal "github.com/chronicle-labs-ai/chronicle-go/internal"
	option "github.com/chronicle-labs-ai/chronicle-go/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) ListEnvironments(
	ctx context.Context,
	opts ...option.RequestOption,
) (*core.Response[*chroniclego.ListEnvironmentsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.chroniclelabs.ai",
	)
	endpointURL := baseURL + "/v1/environments"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *chroniclego.ListEnvironmentsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(chroniclego.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*chroniclego.ListEnvironmentsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateEnvironment(
	ctx context.Context,
	request *chroniclego.CreateEnvironmentRequest,
	opts ...option.RequestOption,
) (*core.Response[*chroniclego.EnvironmentResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.chroniclelabs.ai",
	)
	endpointURL := baseURL + "/v1/environments"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *chroniclego.EnvironmentResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(chroniclego.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*chroniclego.EnvironmentResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetEnvironment(
	ctx context.Context,
	request *chroniclego.GetEnvironmentRequest,
	opts ...option.RequestOption,
) (*core.Response[*chroniclego.EnvironmentResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.chroniclelabs.ai",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/environments/%v",
		request.EnvironmentID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *chroniclego.EnvironmentResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(chroniclego.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*chroniclego.EnvironmentResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ListEnvironmentVersions(
	ctx context.Context,
	request *chroniclego.ListEnvironmentVersionsRequest,
	opts ...option.RequestOption,
) (*core.Response[[]*chroniclego.EnvironmentVersionRecord], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.chroniclelabs.ai",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/environments/%v/versions",
		request.EnvironmentID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response []*chroniclego.EnvironmentVersionRecord
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(chroniclego.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[[]*chroniclego.EnvironmentVersionRecord]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateEnvironmentVersion(
	ctx context.Context,
	request *chroniclego.CreateEnvironmentVersionRequest,
	opts ...option.RequestOption,
) (*core.Response[*chroniclego.EnvironmentVersionResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.chroniclelabs.ai",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/environments/%v/versions",
		request.EnvironmentID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *chroniclego.EnvironmentVersionResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(chroniclego.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*chroniclego.EnvironmentVersionResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetEnvironmentVersion(
	ctx context.Context,
	request *chroniclego.GetEnvironmentVersionRequest,
	opts ...option.RequestOption,
) (*core.Response[*chroniclego.EnvironmentVersionResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.chroniclelabs.ai",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/environments/%v/versions/%v",
		request.EnvironmentID,
		request.VersionSelector,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *chroniclego.EnvironmentVersionResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(chroniclego.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*chroniclego.EnvironmentVersionResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CompileEnvironmentVersion(
	ctx context.Context,
	request *chroniclego.CompileEnvironmentRequest,
	opts ...option.RequestOption,
) (*core.Response[*chroniclego.CompileEnvironmentResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.chroniclelabs.ai",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/environments/%v/versions/%v/compile",
		request.EnvironmentID,
		request.VersionSelector,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *chroniclego.CompileEnvironmentResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(chroniclego.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*chroniclego.CompileEnvironmentResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
