// Code generated by Fern. DO NOT EDIT.

package credentials

import (
	context "context"

	chroniclego "github.com/chronicle-labs-ai/chronicle-go"
	core "github.com/chronicle-labs-ai/chronicle-go/core"
	internal "github.com/chronicle-labs-ai/chronicle-go/internal"
	option "github.com/chronicle-labs-ai/chronicle-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Example:
//
//	client.Credentials.ListSdkKeys(
//	    context.TODO(),
//	)
func (c *Client) ListSdkKeys(
	ctx context.Context,
	opts ...option.RequestOption,
) (*chroniclego.SdkKeyListResponse, error) {
	response, err := c.WithRawResponse.ListSdkKeys(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The bearer secret is returned once and is not stored in plaintext.
//
// Example:
//
//	request := &chroniclego.CreateSdkKeyRequest{
//	    Name: "name",
//	    Scopes: []chroniclego.CreateSdkKeyRequestScopesItem{
//	        chroniclego.CreateSdkKeyRequestScopesItemTracesWrite,
//	    },
//	}
//	client.Credentials.CreateSdkKey(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CreateSdkKey(
	ctx context.Context,
	request *chroniclego.CreateSdkKeyRequest,
	opts ...option.RequestOption,
) (*chroniclego.CreatedSdkKey, error) {
	response, err := c.WithRawResponse.CreateSdkKey(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &chroniclego.RevokeSdkKeyRequest{
//	    KeyID: "key_id",
//	}
//	client.Credentials.RevokeSdkKey(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) RevokeSdkKey(
	ctx context.Context,
	request *chroniclego.RevokeSdkKeyRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.RevokeSdkKey(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
