// Code generated by Fern. DO NOT EDIT.

package links

import (
	context "context"

	chroniclego "github.com/chronicle-labs-ai/chronicle-go"
	core "github.com/chronicle-labs-ai/chronicle-go/core"
	internal "github.com/chronicle-labs-ai/chronicle-go/internal"
	option "github.com/chronicle-labs-ai/chronicle-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Requires scope events:write.
//
// Example:
//
//	request := &chroniclego.AddEntityRefRequest{
//	    EventID: "event_id",
//	    EntityType: "entity_type",
//	    EntityID: "entity_id",
//	}
//	client.Links.AddEntityRef(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) AddEntityRef(
	ctx context.Context,
	request *chroniclego.AddEntityRefRequest,
	opts ...option.RequestOption,
) (*chroniclego.StatusResponse, error) {
	response, err := c.WithRawResponse.AddEntityRef(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Requires scope events:write.
//
// Example:
//
//	request := &chroniclego.CreateLinkRequest{
//	    SourceEventID: "source_event_id",
//	    TargetEventID: "target_event_id",
//	    LinkType: "link_type",
//	    Confidence: 1.1,
//	}
//	client.Links.CreateEventLink(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CreateEventLink(
	ctx context.Context,
	request *chroniclego.CreateLinkRequest,
	opts ...option.RequestOption,
) (*chroniclego.CreateLinkResponse, error) {
	response, err := c.WithRawResponse.CreateEventLink(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Requires scope events:write.
//
// Example:
//
//	request := &chroniclego.LinkEntityRequest{
//	    FromEntityType: "from_entity_type",
//	    FromEntityID: "from_entity_id",
//	    ToEntityType: "to_entity_type",
//	    ToEntityID: "to_entity_id",
//	}
//	client.Links.LinkEntities(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) LinkEntities(
	ctx context.Context,
	request *chroniclego.LinkEntityRequest,
	opts ...option.RequestOption,
) (*chroniclego.LinkEntityResponse, error) {
	response, err := c.WithRawResponse.LinkEntities(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Requires scope events:read or events:write. The traversal is bounded by `max_depth`, is not cursor-paginated, and consumes 5 rate-limit units.
//
// Example:
//
//	request := &chroniclego.GraphRequest{
//	    StartEventID: "start_event_id",
//	    Direction: chroniclego.GraphRequestDirectionOutgoing,
//	}
//	client.Links.TraverseGraph(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) TraverseGraph(
	ctx context.Context,
	request *chroniclego.GraphRequest,
	opts ...option.RequestOption,
) (*chroniclego.EventListResponse, error) {
	response, err := c.WithRawResponse.TraverseGraph(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
