// Code generated by Fern. DO NOT EDIT.

package backtests_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	chroniclego "github.com/chronicle-labs-ai/chronicle-go"
	client "github.com/chronicle-labs-ai/chronicle-go/client"
	option "github.com/chronicle-labs-ai/chronicle-go/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestBacktestsGetBacktestsAvailabilityWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	_, invocationErr := client.Backtests.GetBacktestsAvailability(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBacktestsGetBacktestsAvailabilityWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBacktestsGetBacktestsAvailabilityWithWireMock", "GET", "/v1/backtests/availability", nil, 1)
}

func TestBacktestsListBacktestJobsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &chroniclego.ListBacktestJobsRequest{}
	_, invocationErr := client.Backtests.ListBacktestJobs(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBacktestsListBacktestJobsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBacktestsListBacktestJobsWithWireMock", "GET", "/v1/backtests/jobs", nil, 1)
}

func TestBacktestsCreateBacktestJobWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &chroniclego.CreateBacktestJobRequest{
		Name: "name",
		Recipe: &chroniclego.CreateBacktestJobRequestRecipe{
			Agents: []*chroniclego.CreateBacktestJobRequestRecipeAgentsItem{
				&chroniclego.CreateBacktestJobRequestRecipeAgentsItem{
					Hue:   "hue",
					ID:    "id",
					Label: "label",
					Notes: "notes",
				},
			},
			Data: &chroniclego.CreateBacktestJobRequestRecipeData{
				Kind: chroniclego.CreateBacktestJobRequestRecipeDataKindComposed,
				Scenarios: []*chroniclego.CreateBacktestJobRequestRecipeDataScenariosItem{
					&chroniclego.CreateBacktestJobRequestRecipeDataScenariosItem{
						Count: 1,
						ID:    "id",
						Kind:  chroniclego.CreateBacktestJobRequestRecipeDataScenariosItemKindAdversarial,
						Label: "label",
					},
				},
				Sources: []*chroniclego.CreateBacktestJobRequestRecipeDataSourcesItem{
					&chroniclego.CreateBacktestJobRequestRecipeDataSourcesItem{
						Count: 1,
						ID:    "id",
						Kind:  chroniclego.CreateBacktestJobRequestRecipeDataSourcesItemKindProd,
						Label: "label",
					},
				},
			},
			Graders: []*chroniclego.CreateBacktestJobRequestRecipeGradersItem{
				&chroniclego.CreateBacktestJobRequestRecipeGradersItem{
					ID:     "id",
					Kind:   chroniclego.CreateBacktestJobRequestRecipeGradersItemKindRubric,
					Label:  "label",
					Source: chroniclego.CreateBacktestJobRequestRecipeGradersItemSourceProposed,
					Weight: chroniclego.CreateBacktestJobRequestRecipeGradersItemWeightLow,
				},
			},
			Mode: chroniclego.CreateBacktestJobRequestRecipeModeReplay,
			Name: "name",
		},
	}
	_, invocationErr := client.Backtests.CreateBacktestJob(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBacktestsCreateBacktestJobWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBacktestsCreateBacktestJobWithWireMock", "POST", "/v1/backtests/jobs", nil, 1)
}

func TestBacktestsGetBacktestJobWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &chroniclego.GetBacktestJobRequest{
		JobID: "job_id",
	}
	_, invocationErr := client.Backtests.GetBacktestJob(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBacktestsGetBacktestJobWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBacktestsGetBacktestJobWithWireMock", "GET", "/v1/backtests/jobs/job_id", nil, 1)
}

func TestBacktestsListBacktestJobTrialsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &chroniclego.ListBacktestJobTrialsRequest{
		JobID: "job_id",
	}
	_, invocationErr := client.Backtests.ListBacktestJobTrials(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBacktestsListBacktestJobTrialsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBacktestsListBacktestJobTrialsWithWireMock", "GET", "/v1/backtests/jobs/job_id/trials", nil, 1)
}

func TestBacktestsGetBacktestTrialWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &chroniclego.GetBacktestTrialRequest{
		JobID:   "job_id",
		TrialID: "trial_id",
	}
	_, invocationErr := client.Backtests.GetBacktestTrial(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBacktestsGetBacktestTrialWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBacktestsGetBacktestTrialWithWireMock", "GET", "/v1/backtests/jobs/job_id/trials/trial_id", nil, 1)
}

func TestBacktestsCancelBacktestJobWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &chroniclego.CancelBacktestJobRequest{
		JobID: "job_id",
	}
	_, invocationErr := client.Backtests.CancelBacktestJob(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBacktestsCancelBacktestJobWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBacktestsCancelBacktestJobWithWireMock", "POST", "/v1/backtests/jobs/job_id/cancel", nil, 1)
}

func TestBacktestsStreamBacktestJobEventsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &chroniclego.StreamBacktestJobEventsRequest{
		JobID: "job_id",
	}
	_, invocationErr := client.Backtests.StreamBacktestJobEvents(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBacktestsStreamBacktestJobEventsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBacktestsStreamBacktestJobEventsWithWireMock", "GET", "/v1/backtests/jobs/job_id/stream", nil, 1)
}
