// Code generated by Fern. DO NOT EDIT.

package agents_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	chroniclego "github.com/chronicle-labs-ai/chronicle-go"
	client "github.com/chronicle-labs-ai/chronicle-go/client"
	option "github.com/chronicle-labs-ai/chronicle-go/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestAgentsListAgentsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	_, invocationErr := client.Agents.ListAgents(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAgentsListAgentsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAgentsListAgentsWithWireMock", "GET", "/v1/agents", nil, 1)
}

func TestAgentsSearchAgentHashIndexWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &chroniclego.SearchAgentHashIndexRequest{}
	_, invocationErr := client.Agents.SearchAgentHashIndex(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAgentsSearchAgentHashIndexWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAgentsSearchAgentHashIndexWithWireMock", "GET", "/v1/agents/hash-index", nil, 1)
}

func TestAgentsSubscribeToAgentChangesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	_, invocationErr := client.Agents.SubscribeToAgentChanges(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAgentsSubscribeToAgentChangesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAgentsSubscribeToAgentChangesWithWireMock", "GET", "/v1/agents/subscribe", nil, 1)
}

func TestAgentsUpdateAgentWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &chroniclego.UpdateAgentRequest{
		Name: "name",
	}
	_, invocationErr := client.Agents.UpdateAgent(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAgentsUpdateAgentWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAgentsUpdateAgentWithWireMock", "PATCH", "/v1/agents/name", nil, 1)
}

func TestAgentsGetAgentSnapshotWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &chroniclego.GetAgentSnapshotRequest{
		Name: "name",
	}
	_, invocationErr := client.Agents.GetAgentSnapshot(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAgentsGetAgentSnapshotWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAgentsGetAgentSnapshotWithWireMock", "GET", "/v1/agents/name/snapshot", nil, 1)
}

func TestAgentsPinLatestAgentVersionWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &chroniclego.PinLatestAgentVersionRequest{
		Name: "name",
	}
	_, invocationErr := client.Agents.PinLatestAgentVersion(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAgentsPinLatestAgentVersionWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAgentsPinLatestAgentVersionWithWireMock", "POST", "/v1/agents/name/pin-latest", nil, 1)
}

func TestAgentsCreateAgentChatSessionWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &chroniclego.CreateAgentChatSessionRequest{
		Name: "name",
	}
	_, invocationErr := client.Agents.CreateAgentChatSession(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAgentsCreateAgentChatSessionWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAgentsCreateAgentChatSessionWithWireMock", "POST", "/v1/agents/name/chat/sessions", nil, 1)
}

func TestAgentsGetAgentChatSessionWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &chroniclego.GetAgentChatSessionRequest{
		Name:      "name",
		SessionID: "session_id",
	}
	_, invocationErr := client.Agents.GetAgentChatSession(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAgentsGetAgentChatSessionWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAgentsGetAgentChatSessionWithWireMock", "GET", "/v1/agents/name/chat/sessions/session_id", nil, 1)
}

func TestAgentsSendAgentChatMessageWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &chroniclego.SendAgentChatMessageRequest{
		Name:      "name",
		SessionID: "session_id",
		Text:      "text",
	}
	_, invocationErr := client.Agents.SendAgentChatMessage(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAgentsSendAgentChatMessageWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAgentsSendAgentChatMessageWithWireMock", "POST", "/v1/agents/name/chat/sessions/session_id/messages", nil, 1)
}

func TestAgentsRegisterAgentArtifactWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &chroniclego.RegisterAgentArtifactRequest{
		Artifact: &chroniclego.RegisterAgentArtifactRequestArtifact{
			ArtifactID: "artifactId",
			ConfigHash: "configHash",
			Framework:  chroniclego.RegisterAgentArtifactRequestArtifactFrameworkVercelAiSdk,
			Model: &chroniclego.RegisterAgentArtifactRequestArtifactModel{
				Label: "label",
			},
			Name: "name",
			Provenance: &chroniclego.RegisterAgentArtifactRequestArtifactProvenance{
				CreatedAt: chroniclego.MustParseDateTime(
					"2024-01-15T09:30:00Z",
				),
			},
			SchemaVersion: "schemaVersion",
			Tools: []*chroniclego.RegisterAgentArtifactRequestArtifactToolsItem{
				&chroniclego.RegisterAgentArtifactRequestArtifactToolsItem{
					Name: "name",
				},
			},
			Version: "version",
		},
	}
	_, invocationErr := client.Agents.RegisterAgentArtifact(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAgentsRegisterAgentArtifactWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAgentsRegisterAgentArtifactWithWireMock", "POST", "/v1/agents/register", nil, 1)
}

func TestAgentsRecordAgentRunsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &chroniclego.RecordAgentRunsRequest{
		Runs: []*chroniclego.RecordAgentRunsRequestRunsItem{
			&chroniclego.RecordAgentRunsRequestRunsItem{
				ArtifactID:    "artifactId",
				ConfigHash:    "configHash",
				Operation:     chroniclego.RecordAgentRunsRequestRunsItemOperationGenerate,
				RunID:         "runId",
				SchemaVersion: "schemaVersion",
				StartedAt: chroniclego.MustParseDateTime(
					"2024-01-15T09:30:00Z",
				),
				Status: chroniclego.RecordAgentRunsRequestRunsItemStatusStarted,
				ToolCalls: []*chroniclego.RecordAgentRunsRequestRunsItemToolCallsItem{
					&chroniclego.RecordAgentRunsRequestRunsItemToolCallsItem{
						CallID: "callId",
						StartedAt: chroniclego.MustParseDateTime(
							"2024-01-15T09:30:00Z",
						),
						Status:   chroniclego.RecordAgentRunsRequestRunsItemToolCallsItemStatusStarted,
						ToolName: "toolName",
					},
				},
			},
		},
	}
	_, invocationErr := client.Agents.RecordAgentRuns(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAgentsRecordAgentRunsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAgentsRecordAgentRunsWithWireMock", "POST", "/v1/agents/runs/batch", nil, 1)
}
